# Generated by Django 5.1.7 on 2026-01-18 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaHumana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('cuil_cuit', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('', '- Seleccionar -'), ('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('O', 'Otro')], max_length=10)),
                ('nivel_educativo', models.CharField(choices=[('', '- Seleccionar -'), ('Pc', 'Primario completo'), ('Sc', 'Secundario completo'), ('Tc', 'Terciario completo'), ('Uc', 'Universitario completo'), ('Pos', 'Posgrado completo')], max_length=50, verbose_name='Nivel educativo alcanzado')),
                ('lugar_residencia', models.CharField(choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EP', 'El Potrero'), ('EQ', 'El Quebrachal'), ('ET', 'El Tala'), ('Em', 'Embarcación'), ('GG', 'General Güemes'), ('GP', 'General Pizzarro'), ('GM', 'General Mosconi'), ('GB', 'General Ballivián'), ('Gu', 'Guachipas'), ('HI', 'Hipólito Yrigoyen'), ('Ir', 'Iruya'), ('IC', 'Isla de Cañas'), ('JVG', 'Joaquín V. Gonzalez'), ('LC', 'La Caldera'), ('LCa', 'La Candelaria'), ('LM', 'La Merced'), ('LP', 'La Poma'), ('LV', 'La Viña'), ('LL', 'Las Lajitas'), ('LT', 'Los Toldos'), ('Mo', 'Molinos'), ('Na', 'Nazareno'), ('Pa', 'Payogasta'), ('PSM', 'Profesor Salvador Mazza'), ('RP', 'Río Piedras'), ('RBN', 'Rivadavia Banda Norte'), ('RBS', 'Rivadavia Banda Sur'), ('SAC', 'San Antonio de los Cobres'), ('SC', 'San Carlos'), ('SJM', 'San José de Metán'), ('SL', 'San Lorenzo'), ('Or', 'San Ramón de la Nueva Orán'), ('SVE', 'Santa Victoria Este'), ('SVO', 'Santa Victoria Oeste'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('TG', 'Tolar Grande'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], max_length=100)),
                ('otro_lugar_residencia', models.CharField(blank=True, max_length=150, null=True)),
                ('domicilio_real', models.CharField(max_length=250)),
                ('codigo_postal_real', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('situacion_iva', models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('N', 'Ninguna'), ('EX', 'Exento'), ('M', 'Monotributista'), ('RI', 'Responsable Inscripto'), ('O', 'Otra')], max_length=5, null=True)),
                ('actividad_dgr', models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('591110', '591110 - Producción de filmes y videocintas'), ('591120', '591120 - Postproducción de filmes y videocintas'), ('O', 'Otra'), ('N', 'Ninguna')], max_length=10, null=True)),
                ('domicilio_fiscal', models.CharField(blank=True, max_length=250, null=True)),
                ('codigo_postal_fiscal', models.CharField(blank=True, max_length=10, null=True)),
                ('localidad_fiscal', models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EP', 'El Potrero'), ('EQ', 'El Quebrachal'), ('ET', 'El Tala'), ('Em', 'Embarcación'), ('GG', 'General Güemes'), ('GP', 'General Pizzarro'), ('GM', 'General Mosconi'), ('GB', 'General Ballivián'), ('Gu', 'Guachipas'), ('HI', 'Hipólito Yrigoyen'), ('Ir', 'Iruya'), ('IC', 'Isla de Cañas'), ('JVG', 'Joaquín V. Gonzalez'), ('LC', 'La Caldera'), ('LCa', 'La Candelaria'), ('LM', 'La Merced'), ('LP', 'La Poma'), ('LV', 'La Viña'), ('LL', 'Las Lajitas'), ('LT', 'Los Toldos'), ('Mo', 'Molinos'), ('Na', 'Nazareno'), ('Pa', 'Payogasta'), ('PSM', 'Profesor Salvador Mazza'), ('RP', 'Río Piedras'), ('RBN', 'Rivadavia Banda Norte'), ('RBS', 'Rivadavia Banda Sur'), ('SAC', 'San Antonio de los Cobres'), ('SC', 'San Carlos'), ('SJM', 'San José de Metán'), ('SL', 'San Lorenzo'), ('Or', 'San Ramón de la Nueva Orán'), ('SVE', 'Santa Victoria Este'), ('SVO', 'Santa Victoria Oeste'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('TG', 'Tolar Grande'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], max_length=100, null=True)),
                ('area_desempeno_1', models.CharField(choices=[('', '- Seleccionar -'), ('Productor', 'Productor/a'), ('Jefe_prod', 'Jefe/a de producción'), ('Asist_prod', 'Asistente de producción'), ('Jefe_loc', 'Jefe/a de locaciones'), ('Director', 'Director/a'), ('Asist_Dir', 'Asistente de dirección'), ('Dir_Cast', 'Director/a de casting'), ('Dir_Foto', 'Director/a de fotografía'), ('Camara', 'Camarógrafo/a'), ('Key_Grip', 'Key Grip'), ('Video Asist_DIT', 'Video Asist / DIT<'), ('Gaffer', 'Gaffer'), ('Guionista', 'Guionista'), ('Reflec', 'Reflectorista'), ('Dir_Arte', 'Dirección de Arte'), ('Escnog', 'Escenógrafo/a'), ('Vest', 'Vestuarista'), ('Maqui', 'Jefe/a de Maquillaje'), ('Dir_Son', 'Dirección de Sonido'), ('Ayu_Son', 'Ayudante de Sonido '), ('Dir_Son_Post', 'Dirección de Sonido Post / Mezclador/a'), ('Post_Prod', 'Postproductor/a'), ('Editor', 'Editor/a'), ('Color', 'Colorista'), ('Animam', 'Animador/a'), ('Realizador', 'Realizador/a integral'), ('Game_Design', 'Game Designer'), ('Game_Artist', 'Game Artist'), ('otro', 'Otro')], max_length=50, verbose_name='Área de desempeño principal')),
                ('area_desempeno_2', models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('Productor', 'Productor/a'), ('Jefe_prod', 'Jefe/a de producción'), ('Asist_prod', 'Asistente de producción'), ('Jefe_loc', 'Jefe/a de locaciones'), ('Director', 'Director/a'), ('Asist_Dir', 'Asistente de dirección'), ('Dir_Cast', 'Director/a de casting'), ('Dir_Foto', 'Director/a de fotografía'), ('Camara', 'Camarógrafo/a'), ('Key_Grip', 'Key Grip'), ('Video Asist_DIT', 'Video Asist / DIT<'), ('Gaffer', 'Gaffer'), ('Guionista', 'Guionista'), ('Reflec', 'Reflectorista'), ('Dir_Arte', 'Dirección de Arte'), ('Escnog', 'Escenógrafo/a'), ('Vest', 'Vestuarista'), ('Maqui', 'Jefe/a de Maquillaje'), ('Dir_Son', 'Dirección de Sonido'), ('Ayu_Son', 'Ayudante de Sonido '), ('Dir_Son_Post', 'Dirección de Sonido Post / Mezclador/a'), ('Post_Prod', 'Postproductor/a'), ('Editor', 'Editor/a'), ('Color', 'Colorista'), ('Animam', 'Animador/a'), ('Realizador', 'Realizador/a integral'), ('Game_Design', 'Game Designer'), ('Game_Artist', 'Game Artist'), ('otro', 'Otro')], max_length=50, null=True, verbose_name='Área de desempeño secundaria')),
                ('area_cultural', models.CharField(choices=[('', '- Seleccionar -'), ('Actor', 'Actror / Actríz'), ('musica', 'Música'), ('danza', 'Danza'), ('literatura', 'Literatura'), ('visuales', 'Artes Visuales'), ('comunicacion', 'Comunicación'), ('locutor', 'Locutor/a'), ('educacion', 'Educación'), ('ninguna', 'Ninguna'), ('otro', 'Otro')], max_length=50, verbose_name='Área cultural complementaria')),
                ('portfolio_web', models.CharField(blank=True, default='', help_text='Sitio web personal, de la productora o portfolio online (Vimeo, Behance, etc.)', max_length=300, verbose_name='Sitio web / Portfolio')),
                ('canal_video', models.CharField(blank=True, default='', help_text='Canal de YouTube, Vimeo u otra plataforma de video', max_length=300, verbose_name='Canal audiovisual')),
                ('instagram', models.CharField(blank=True, default='', help_text='Perfil de Instagram profesional', max_length=300, verbose_name='Instagram')),
                ('linkedin', models.CharField(blank=True, default='', help_text='Perfil de LinkedIn', max_length=300, verbose_name='LinkedIn')),
                ('link_trabajo_destacado', models.CharField(blank=True, default='', help_text='Link a una obra o trabajo audiovisual relevante', max_length=300, verbose_name='Trabajo destacado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_humana', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona_juridica', models.CharField(choices=[('asociacion', 'Asociación Civil'), ('fundacion', 'Fundación'), ('empresa', 'Empresa'), ('cooperativa', 'Cooperativa')], max_length=100)),
                ('cuil_cuit', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True)),
                ('domicilio_fiscal', models.CharField(max_length=250)),
                ('localidad_fiscal', models.CharField(choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EP', 'El Potrero'), ('EQ', 'El Quebrachal'), ('ET', 'El Tala'), ('Em', 'Embarcación'), ('GG', 'General Güemes'), ('GP', 'General Pizzarro'), ('GM', 'General Mosconi'), ('GB', 'General Ballivián'), ('Gu', 'Guachipas'), ('HI', 'Hipólito Yrigoyen'), ('Ir', 'Iruya'), ('IC', 'Isla de Cañas'), ('JVG', 'Joaquín V. Gonzalez'), ('LC', 'La Caldera'), ('LCa', 'La Candelaria'), ('LM', 'La Merced'), ('LP', 'La Poma'), ('LV', 'La Viña'), ('LL', 'Las Lajitas'), ('LT', 'Los Toldos'), ('Mo', 'Molinos'), ('Na', 'Nazareno'), ('Pa', 'Payogasta'), ('PSM', 'Profesor Salvador Mazza'), ('RP', 'Río Piedras'), ('RBN', 'Rivadavia Banda Norte'), ('RBS', 'Rivadavia Banda Sur'), ('SAC', 'San Antonio de los Cobres'), ('SC', 'San Carlos'), ('SJM', 'San José de Metán'), ('SL', 'San Lorenzo'), ('Or', 'San Ramón de la Nueva Orán'), ('SVE', 'Santa Victoria Este'), ('SVO', 'Santa Victoria Oeste'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('TG', 'Tolar Grande'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], max_length=100)),
                ('codigo_postal_fiscal', models.CharField(max_length=10)),
                ('situacion_iva', models.CharField(choices=[('', '- Seleccionar -'), ('N', 'Ninguna'), ('EX', 'Exento'), ('M', 'Monotributista'), ('RI', 'Responsable Inscripto'), ('O', 'Otra')], max_length=5)),
                ('actividad_dgr', models.CharField(choices=[('', '- Seleccionar -'), ('591110', '591110 - Producción de filmes y videocintas'), ('591120', '591120 - Postproducción de filmes y videocintas'), ('O', 'Otra'), ('N', 'Ninguna')], max_length=10)),
                ('fecha_constitucion', models.DateField()),
                ('antiguedad', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('area_desempeno_JJPP_1', models.CharField(choices=[('', '- Seleccionar -'), ('', '- Empresas -'), ('Productora', 'Empresa de producción'), ('PostProd', 'Empresa de postproducción'), ('Serv_Prod', 'Empresa de servicios para la producción'), ('', '- Personas Jurídicas s/fines de lucro -'), ('PPJJ_Espec', 'Específica Audiovisual '), ('PPJJ_Cult', 'Cultural'), ('otro', 'Otro')], max_length=50, verbose_name='Área de desempeño principal')),
                ('area_desempeno_JJPP_2', models.CharField(choices=[('', '- Seleccionar -'), ('', '- Empresas -'), ('Productora', 'Empresa de producción'), ('PostProd', 'Empresa de postproducción'), ('Serv_Prod', 'Empresa de servicios para la producción'), ('', '- Personas Jurídicas s/fines de lucro -'), ('PPJJ_Espec', 'Específica Audiovisual '), ('PPJJ_Cult', 'Cultural'), ('otro', 'Otro')], max_length=50, verbose_name='Área de desempeño secundaria')),
                ('portfolio_web', models.CharField(blank=True, default='', help_text='Sitio web personal, de la productora o portfolio online (Vimeo, Behance, etc.)', max_length=300, verbose_name='Sitio web / Portfolio')),
                ('canal_video', models.CharField(blank=True, default='', help_text='Canal de YouTube, Vimeo u otra plataforma de video', max_length=300, verbose_name='Canal audiovisual')),
                ('instagram', models.CharField(blank=True, default='', help_text='Perfil de Instagram profesional', max_length=300, verbose_name='Instagram')),
                ('linkedin', models.CharField(blank=True, default='', help_text='Perfil de LinkedIn', max_length=300, verbose_name='LinkedIn')),
                ('link_trabajo_destacado', models.CharField(blank=True, default='', help_text='Link a una obra o trabajo audiovisual relevante', max_length=300, verbose_name='Trabajo destacado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_juridica', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
