# Generated by Django 5.2.8 on 2025-11-27 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaHumana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cuil_cuit', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('lugar_residencia', models.CharField(choices=[('AGUARAY', 'Aguaray'), ('AGUAS_BLANCAS', 'Aguas Blancas'), ('OTRO', 'Otro')], max_length=50)),
                ('residencia_otro', models.CharField(blank=True, help_text="Completar solo si seleccionaste 'Otro' en lugar de residencia.", max_length=255, null=True)),
                ('domicilio_real', models.CharField(max_length=255)),
                ('telefono_contacto', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('MUJER', 'Mujer'), ('VARON', 'Varón'), ('NO_DICE', 'Prefiero no decirlo'), ('X', 'X'), ('OTRA', 'Mi género se ve representado por otra identidad')], max_length=20)),
                ('nivel_educativo', models.CharField(choices=[('PRIMARIO', 'Primario completo'), ('SECUNDARIO', 'Secundario completo'), ('TERCIARIO', 'Terciario completo'), ('UNIVERSITARIO', 'Universitario completo'), ('POSGRADO', 'Posgrado completo')], max_length=20)),
                ('area_desempeno_1', models.CharField(choices=[('PRODUCTOR', 'Productor/a'), ('JEFE_PRODUCCION', 'Jefe de producción')], max_length=50)),
                ('area_desempeno_2', models.CharField(blank=True, choices=[('PRODUCTOR', 'Productor/a'), ('JEFE_PRODUCCION', 'Jefe de producción')], max_length=50, null=True)),
                ('area_desempeno_3', models.CharField(blank=True, choices=[('PRODUCTOR', 'Productor/a'), ('JEFE_PRODUCCION', 'Jefe de producción')], max_length=50, null=True)),
                ('area_cultural_complementaria', models.CharField(blank=True, max_length=255, null=True)),
                ('medios_experiencia', models.CharField(blank=True, max_length=255, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_persona_juridica', models.CharField(choices=[('EMPRESA', 'Empresa'), ('ASOC_CIVIL', 'Asociación civil'), ('FUNDACION', 'Fundación'), ('COOPERATIVA', 'Cooperativa de trabajo'), ('OTRA', 'Otra')], max_length=20)),
                ('area_desempeno_1', models.CharField(max_length=50)),
                ('area_desempeno_2', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PerfilAudiovisual',
        ),
    ]
