# Generated by Django 5.1.7 on 2025-12-08 01:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0002_personahumana_personajuridica_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personahumana',
            old_name='correo_electronico',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='personahumana',
            old_name='telefono_contacto',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='personajuridica',
            old_name='area_desempeno_1',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='personahumana',
            name='area_cultural_complementaria',
        ),
        migrations.RemoveField(
            model_name='personahumana',
            name='area_desempeno_3',
        ),
        migrations.RemoveField(
            model_name='personahumana',
            name='links',
        ),
        migrations.RemoveField(
            model_name='personahumana',
            name='residencia_otro',
        ),
        migrations.RemoveField(
            model_name='personahumana',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personajuridica',
            name='area_desempeno_2',
        ),
        migrations.RemoveField(
            model_name='personajuridica',
            name='user',
        ),
        migrations.AddField(
            model_name='personahumana',
            name='actividad_dgr',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('PF', '591110 - Producción de filmes y videocintas'), ('PPF', '591120 - Postproducción de filmes y videocintas'), ('O', 'Otra'), ('N', 'Ninguna')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personahumana',
            name='area_cultural',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('Actor', 'Actror / Actríz'), ('musica', 'Música'), ('danza', 'Danza'), ('literatura', 'Literatura'), ('visuales', 'Artes Visuales'), ('comunicacion', 'Comunicación'), ('locutor', 'Locutor/a'), ('educacion', 'Educación'), ('otro', 'Otro')], default='', max_length=50, verbose_name='Área cultural complementaria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personahumana',
            name='domicilio_fiscal',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='personahumana',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personahumana',
            name='otro_lugar_residencia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personahumana',
            name='situacion_iva',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('N', 'Ninguna'), ('EX', 'Exento'), ('M', 'Monotributista'), ('RI', 'Responsable Inscripto'), ('O', 'Otra')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='actividad_dgr',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('PF', '591110 - Producción de filmes y videocintas'), ('PPF', '591120 - Postproducción de filmes y videocintas'), ('O', 'Otra'), ('N', 'Ninguna')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='antiguedad',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='area_desempeno_JJPP_1',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('', '- Empresas -'), ('Productora', 'Empresa de producción'), ('PostProd', 'Empresa de postproducción'), ('Serv_Prod', 'Empresa de servicios para la producción'), ('', '- Personas Jurídicas s/fines de lucro -'), ('PPJJ_Espec', 'Específica Audiovisual '), ('PPJJ_Cult', 'Cultural'), ('otro', 'Otro')], default='', max_length=50, verbose_name='Área de desempeño PPJJ 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='area_desempeno_JJPP_2',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('', '- Empresas -'), ('Productora', 'Empresa de producción'), ('PostProd', 'Empresa de postproducción'), ('Serv_Prod', 'Empresa de servicios para la producción'), ('', '- Personas Jurídicas s/fines de lucro -'), ('PPJJ_Espec', 'Específica Audiovisual '), ('PPJJ_Cult', 'Cultural'), ('otro', 'Otro')], default='', max_length=50, verbose_name='Área de desempeño PPJJ 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='cuil_cuit',
            field=models.CharField(default='000000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='domicilio_fiscal',
            field=models.CharField(default='Sin domicilio fiscal', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='email',
            field=models.EmailField(default='sin-email@ejemplo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='fecha_constitucion',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='lugar_residencia',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EP', 'El Potrero'), ('EQ', 'El Quebrachal'), ('ET', 'El Tala'), ('Em', 'Embarcación'), ('GG', 'General Güemes'), ('GP', 'General Pizzarro'), ('GM', 'General Mosconi'), ('GB', 'General Ballivián'), ('Gu', 'Guachipas'), ('HI', 'Hipólito Yrigoyen'), ('Ir', 'Iruya'), ('IC', 'Isla de Cañas'), ('JVG', 'Joaquín V. Gonzalez'), ('LC', 'La Caldera'), ('LCa', 'La Candelaria'), ('LM', 'La Merced'), ('LP', 'La Poma'), ('LV', 'La Viña'), ('LL', 'Las Lajitas'), ('LT', 'Los Toldos'), ('Mo', 'Molinos'), ('Na', 'Nazareno'), ('Pa', 'Payogasta'), ('PSM', 'Profesor Salvador Mazza'), ('RP', 'Río Piedras'), ('RBN', 'Rivadavia Banda Norte'), ('RBS', 'Rivadavia Banda Sur'), ('SAC', 'San Antonio de los Cobres'), ('SC', 'San Carlos'), ('SJM', 'San José de Metán'), ('SL', 'San Lorenzo'), ('Or', 'San Ramón de la Nueva Orán'), ('SVE', 'Santa Victoria Este'), ('SVO', 'Santa Victoria Oeste'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('TG', 'Tolar Grande'), ('Ur', 'Urundel'), ('Va', 'Vaqueros'), ('otro', 'Otro')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='medios_experiencia',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('tv', 'Televisión'), ('cine', 'Cine'), ('web', 'Plataformas web'), ('institucional', 'Contenido institucional'), ('publicidad', 'Publicidad'), ('otro', 'Otro')], default='', max_length=50, verbose_name='Medios con experiencia comprobable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='otro_lugar_residencia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='situacion_iva',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('N', 'Ninguna'), ('EX', 'Exento'), ('M', 'Monotributista'), ('RI', 'Responsable Inscripto'), ('O', 'Otra')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='area_desempeno_1',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('Productor', 'Productor/a'), ('Jefe_prod', 'Jefe/a de producción'), ('Asist_prod', 'Asistente de producción'), ('Jefe_loc', 'Jefe/a de locaciones'), ('Director', 'Director/a'), ('Asist_Dir', 'Asistente de dirección'), ('Dir_Cast', 'Director/a de casting'), ('Dir_Foto', 'Director/a de fotografía'), ('Camara', 'Camarógrafo/a'), ('Key_Grip', 'Key Grip'), ('Video Asist_DIT', 'Video Asist / DIT<'), ('Gaffer', 'Gaffer'), ('Guionista', 'Guionista'), ('Reflec', 'Reflectorista'), ('Dir_Arte', 'Dirección de Arte'), ('Escnog', 'Escenógrafo/a'), ('Vest', 'Vestuarista'), ('Maqui', 'Jefe/a de Maquillaje'), ('Dir_Son', 'Dirección de Sonido'), ('Ayu_Son', 'Ayudante de Sonido '), ('Dir_Son_Post', 'Dirección de Sonido Post / Mezclador/a'), ('Post_Prod', 'Postproductor/a'), ('Editor', 'Editor/a'), ('Color', 'Colorista'), ('Animam', 'Animador/a'), ('Realizador', 'Realizador/a integral'), ('Game_Design', 'Game Designer'), ('Game_Artist', 'Game Artist'), ('otro', 'Otro')], max_length=50, verbose_name='Área de desempeño 1'),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='area_desempeno_2',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('Productor', 'Productor/a'), ('Jefe_prod', 'Jefe/a de producción'), ('Asist_prod', 'Asistente de producción'), ('Jefe_loc', 'Jefe/a de locaciones'), ('Director', 'Director/a'), ('Asist_Dir', 'Asistente de dirección'), ('Dir_Cast', 'Director/a de casting'), ('Dir_Foto', 'Director/a de fotografía'), ('Camara', 'Camarógrafo/a'), ('Key_Grip', 'Key Grip'), ('Video Asist_DIT', 'Video Asist / DIT<'), ('Gaffer', 'Gaffer'), ('Guionista', 'Guionista'), ('Reflec', 'Reflectorista'), ('Dir_Arte', 'Dirección de Arte'), ('Escnog', 'Escenógrafo/a'), ('Vest', 'Vestuarista'), ('Maqui', 'Jefe/a de Maquillaje'), ('Dir_Son', 'Dirección de Sonido'), ('Ayu_Son', 'Ayudante de Sonido '), ('Dir_Son_Post', 'Dirección de Sonido Post / Mezclador/a'), ('Post_Prod', 'Postproductor/a'), ('Editor', 'Editor/a'), ('Color', 'Colorista'), ('Animam', 'Animador/a'), ('Realizador', 'Realizador/a integral'), ('Game_Design', 'Game Designer'), ('Game_Artist', 'Game Artist'), ('otro', 'Otro')], default='', max_length=50, verbose_name='Área de desempeño 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='domicilio_real',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='edad',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='genero',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('O', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='lugar_residencia',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EP', 'El Potrero'), ('EQ', 'El Quebrachal'), ('ET', 'El Tala'), ('Em', 'Embarcación'), ('GG', 'General Güemes'), ('GP', 'General Pizzarro'), ('GM', 'General Mosconi'), ('GB', 'General Ballivián'), ('Gu', 'Guachipas'), ('HI', 'Hipólito Yrigoyen'), ('Ir', 'Iruya'), ('IC', 'Isla de Cañas'), ('JVG', 'Joaquín V. Gonzalez'), ('LC', 'La Caldera'), ('LCa', 'La Candelaria'), ('LM', 'La Merced'), ('LP', 'La Poma'), ('LV', 'La Viña'), ('LL', 'Las Lajitas'), ('LT', 'Los Toldos'), ('Mo', 'Molinos'), ('Na', 'Nazareno'), ('Pa', 'Payogasta'), ('PSM', 'Profesor Salvador Mazza'), ('RP', 'Río Piedras'), ('RBN', 'Rivadavia Banda Norte'), ('RBS', 'Rivadavia Banda Sur'), ('SAC', 'San Antonio de los Cobres'), ('SC', 'San Carlos'), ('SJM', 'San José de Metán'), ('SL', 'San Lorenzo'), ('Or', 'San Ramón de la Nueva Orán'), ('SVE', 'Santa Victoria Este'), ('SVO', 'Santa Victoria Oeste'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('TG', 'Tolar Grande'), ('Ur', 'Urundel'), ('Va', 'Vaqueros'), ('otro', 'Otro')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='medios_experiencia',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('tv', 'Televisión'), ('cine', 'Cine'), ('web', 'Plataformas web'), ('institucional', 'Contenido institucional'), ('publicidad', 'Publicidad'), ('otro', 'Otro')], default='', max_length=50, verbose_name='Medios con experiencia comprobable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='nivel_educativo',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('Pc', 'Primario completo'), ('Sc', 'Secundario completo'), ('Tc', 'Terciario completo'), ('Uc', 'Universitario completo'), ('Pos', 'Posgrado completo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='nombre_completo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='razon_social',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='tipo_persona_juridica',
            field=models.CharField(choices=[('asociacion', 'Asociación Civil'), ('fundacion', 'Fundación'), ('empresa', 'Empresa'), ('cooperativa', 'Cooperativa')], max_length=100),
        ),
    ]
