# Generated by Django 5.1.7 on 2026-03-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0002_alter_personahumana_localidad_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personahumana',
            name='actividad_dgr',
            field=models.CharField(blank=True, choices=[('591110', '591110 - Producción de filmes y videocintas'), ('591120', '591120 - Postproducción de filmes y videocintas'), ('O', 'Otra'), ('N', 'Ninguna')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='area_cultural',
            field=models.CharField(choices=[('Actor', 'Actor / Actriz'), ('musica', 'Música'), ('danza', 'Danza'), ('literatura', 'Literatura'), ('visuales', 'Artes Visuales'), ('comunicacion', 'Comunicación'), ('locutor', 'Locutor/a'), ('educacion', 'Educación'), ('ninguna', 'Ninguna'), ('otro', 'Otro')], max_length=50, verbose_name='Área cultural complementaria'),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='area_desempeno_1',
            field=models.CharField(choices=[('Productor', 'Productor/a'), ('Jefe_prod', 'Jefe/a de producción'), ('Asist_prod', 'Asistente de producción'), ('Jefe_loc', 'Jefe/a de locaciones'), ('Director', 'Director/a'), ('Asist_Dir', 'Asistente de dirección'), ('Dir_Cast', 'Director/a de casting'), ('Dir_Foto', 'Director/a de fotografía'), ('Camara', 'Camarógrafo/a'), ('Key_Grip', 'Key Grip'), ('Video_Asist_DIT', 'Video Asist / DIT'), ('Gaffer', 'Gaffer'), ('Guionista', 'Guionista'), ('Reflec', 'Reflectorista'), ('Dir_Arte', 'Dirección de Arte'), ('Escnog', 'Escenógrafo/a'), ('Vest', 'Vestuarista'), ('Maqui', 'Jefe/a de Maquillaje'), ('Dir_Son', 'Dirección de Sonido'), ('Ayu_Son', 'Ayudante de Sonido'), ('Dir_Son_Post', 'Dirección de Sonido Post / Mezclador/a'), ('Post_Prod', 'Postproductor/a'), ('Editor', 'Editor/a'), ('Color', 'Colorista'), ('Animam', 'Animador/a'), ('Realizador', 'Realizador/a integral'), ('Game_Design', 'Game Designer'), ('Game_Artist', 'Game Artist'), ('otro', 'Otro')], max_length=50, verbose_name='Área de desempeño principal'),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='area_desempeno_2',
            field=models.CharField(blank=True, choices=[('Productor', 'Productor/a'), ('Jefe_prod', 'Jefe/a de producción'), ('Asist_prod', 'Asistente de producción'), ('Jefe_loc', 'Jefe/a de locaciones'), ('Director', 'Director/a'), ('Asist_Dir', 'Asistente de dirección'), ('Dir_Cast', 'Director/a de casting'), ('Dir_Foto', 'Director/a de fotografía'), ('Camara', 'Camarógrafo/a'), ('Key_Grip', 'Key Grip'), ('Video_Asist_DIT', 'Video Asist / DIT'), ('Gaffer', 'Gaffer'), ('Guionista', 'Guionista'), ('Reflec', 'Reflectorista'), ('Dir_Arte', 'Dirección de Arte'), ('Escnog', 'Escenógrafo/a'), ('Vest', 'Vestuarista'), ('Maqui', 'Jefe/a de Maquillaje'), ('Dir_Son', 'Dirección de Sonido'), ('Ayu_Son', 'Ayudante de Sonido'), ('Dir_Son_Post', 'Dirección de Sonido Post / Mezclador/a'), ('Post_Prod', 'Postproductor/a'), ('Editor', 'Editor/a'), ('Color', 'Colorista'), ('Animam', 'Animador/a'), ('Realizador', 'Realizador/a integral'), ('Game_Design', 'Game Designer'), ('Game_Artist', 'Game Artist'), ('otro', 'Otro')], max_length=50, null=True, verbose_name='Área de desempeño secundaria'),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('O', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='localidad_fiscal',
            field=models.CharField(blank=True, choices=[('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EP', 'El Potrero'), ('EQ', 'El Quebrachal'), ('ET', 'El Tala'), ('Em', 'Embarcación'), ('GG', 'General Güemes'), ('GP', 'General Pizarro'), ('GM', 'General Mosconi'), ('GB', 'General Ballivián'), ('Gu', 'Guachipas'), ('HI', 'Hipólito Yrigoyen'), ('Ir', 'Iruya'), ('IC', 'Isla de Cañas'), ('JVG', 'Joaquín V. González'), ('LC', 'La Caldera'), ('LCa', 'La Candelaria'), ('LM', 'La Merced'), ('LP', 'La Poma'), ('LV', 'La Viña'), ('LL', 'Las Lajitas'), ('LT', 'Los Toldos'), ('Mo', 'Molinos'), ('Na', 'Nazareno'), ('Pa', 'Payogasta'), ('PSM', 'Profesor Salvador Mazza'), ('RP', 'Río Piedras'), ('RBN', 'Rivadavia Banda Norte'), ('RBS', 'Rivadavia Banda Sur'), ('SAC', 'San Antonio de los Cobres'), ('SCa', 'San Carlos'), ('SJM', 'San José de Metán'), ('SL', 'San Lorenzo'), ('Or', 'San Ramón de la Nueva Orán'), ('SVE', 'Santa Victoria Este'), ('SVO', 'Santa Victoria Oeste'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('TG', 'Tolar Grande'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='lugar_residencia',
            field=models.CharField(choices=[('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EP', 'El Potrero'), ('EQ', 'El Quebrachal'), ('ET', 'El Tala'), ('Em', 'Embarcación'), ('GG', 'General Güemes'), ('GP', 'General Pizarro'), ('GM', 'General Mosconi'), ('GB', 'General Ballivián'), ('Gu', 'Guachipas'), ('HI', 'Hipólito Yrigoyen'), ('Ir', 'Iruya'), ('IC', 'Isla de Cañas'), ('JVG', 'Joaquín V. González'), ('LC', 'La Caldera'), ('LCa', 'La Candelaria'), ('LM', 'La Merced'), ('LP', 'La Poma'), ('LV', 'La Viña'), ('LL', 'Las Lajitas'), ('LT', 'Los Toldos'), ('Mo', 'Molinos'), ('Na', 'Nazareno'), ('Pa', 'Payogasta'), ('PSM', 'Profesor Salvador Mazza'), ('RP', 'Río Piedras'), ('RBN', 'Rivadavia Banda Norte'), ('RBS', 'Rivadavia Banda Sur'), ('SAC', 'San Antonio de los Cobres'), ('SCa', 'San Carlos'), ('SJM', 'San José de Metán'), ('SL', 'San Lorenzo'), ('Or', 'San Ramón de la Nueva Orán'), ('SVE', 'Santa Victoria Este'), ('SVO', 'Santa Victoria Oeste'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('TG', 'Tolar Grande'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='nivel_educativo',
            field=models.CharField(choices=[('Pc', 'Primario completo'), ('Sc', 'Secundario completo'), ('Tc', 'Terciario completo'), ('Uc', 'Universitario completo'), ('Pos', 'Posgrado completo')], max_length=50, verbose_name='Nivel educativo alcanzado'),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='situacion_iva',
            field=models.CharField(blank=True, choices=[('N', 'Ninguna'), ('EX', 'Exento'), ('M', 'Monotributista'), ('RI', 'Responsable Inscripto'), ('O', 'Otra')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='actividad_dgr',
            field=models.CharField(choices=[('591110', '591110 - Producción de filmes y videocintas'), ('591120', '591120 - Postproducción de filmes y videocintas'), ('O', 'Otra'), ('N', 'Ninguna')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='area_desempeno_JJPP_1',
            field=models.CharField(choices=[('Productora', 'Empresa de producción'), ('PostProd', 'Empresa de postproducción'), ('Serv_Prod', 'Empresa de servicios para la producción'), ('PPJJ_Espec', 'Persona jurídica específica audiovisual'), ('PPJJ_Cult', 'Persona jurídica cultural'), ('otro', 'Otro')], max_length=50, verbose_name='Área de desempeño principal'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='area_desempeno_JJPP_2',
            field=models.CharField(choices=[('Productora', 'Empresa de producción'), ('PostProd', 'Empresa de postproducción'), ('Serv_Prod', 'Empresa de servicios para la producción'), ('PPJJ_Espec', 'Persona jurídica específica audiovisual'), ('PPJJ_Cult', 'Persona jurídica cultural'), ('otro', 'Otro')], max_length=50, verbose_name='Área de desempeño secundaria'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='localidad_fiscal',
            field=models.CharField(choices=[('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EP', 'El Potrero'), ('EQ', 'El Quebrachal'), ('ET', 'El Tala'), ('Em', 'Embarcación'), ('GG', 'General Güemes'), ('GP', 'General Pizarro'), ('GM', 'General Mosconi'), ('GB', 'General Ballivián'), ('Gu', 'Guachipas'), ('HI', 'Hipólito Yrigoyen'), ('Ir', 'Iruya'), ('IC', 'Isla de Cañas'), ('JVG', 'Joaquín V. González'), ('LC', 'La Caldera'), ('LCa', 'La Candelaria'), ('LM', 'La Merced'), ('LP', 'La Poma'), ('LV', 'La Viña'), ('LL', 'Las Lajitas'), ('LT', 'Los Toldos'), ('Mo', 'Molinos'), ('Na', 'Nazareno'), ('Pa', 'Payogasta'), ('PSM', 'Profesor Salvador Mazza'), ('RP', 'Río Piedras'), ('RBN', 'Rivadavia Banda Norte'), ('RBS', 'Rivadavia Banda Sur'), ('SAC', 'San Antonio de los Cobres'), ('SCa', 'San Carlos'), ('SJM', 'San José de Metán'), ('SL', 'San Lorenzo'), ('Or', 'San Ramón de la Nueva Orán'), ('SVE', 'Santa Victoria Este'), ('SVO', 'Santa Victoria Oeste'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('TG', 'Tolar Grande'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='situacion_iva',
            field=models.CharField(choices=[('N', 'Ninguna'), ('EX', 'Exento'), ('M', 'Monotributista'), ('RI', 'Responsable Inscripto'), ('O', 'Otra')], max_length=5),
        ),
    ]
