# Generated by Django 5.1.7 on 2025-12-08 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0003_rename_correo_electronico_personahumana_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personahumana',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_humana', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_juridica', to=settings.AUTH_USER_MODEL),
        ),
    ]
