# Generated by Django 5.1.7 on 2026-06-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0003_alter_personahumana_actividad_dgr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personajuridica',
            name='representante_apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido del representante legal'),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='representante_dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI del representante legal'),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='representante_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del representante legal'),
        ),
    ]
