# Generated by Django 5.1.7 on 2025-12-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0004_personahumana_user_personajuridica_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personahumana',
            name='medios_experiencia',
        ),
        migrations.RemoveField(
            model_name='personajuridica',
            name='medios_experiencia',
        ),
        migrations.AddField(
            model_name='personahumana',
            name='link_1',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personahumana',
            name='link_2',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personahumana',
            name='link_3',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='link_1',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='link_2',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='link_3',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
