# Generated by Django 5.1.7 on 2026-06-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0004_juridica_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='personajuridica',
            name='productor_apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido del productor/a responsable'),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='productor_dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI del productor/a responsable'),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='productor_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del productor/a responsable'),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='representante_cuil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIL/CUIT del socio/a - gerente o autoridad'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='representante_apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido del socio/a - gerente o autoridad'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='representante_dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI del socio/a - gerente o autoridad'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='representante_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del socio/a - gerente o autoridad'),
        ),
    ]
