# Generated by Django 5.1.7 on 2025-12-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0005_remove_personahumana_medios_experiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personahumana',
            name='link_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='link_3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
