# Generated by Django 5.1.7 on 2026-06-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0005_personajuridica_productor_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personajuridica',
            name='productor_apellido',
        ),
        migrations.RemoveField(
            model_name='personajuridica',
            name='productor_dni',
        ),
        migrations.RemoveField(
            model_name='personajuridica',
            name='productor_nombre',
        ),
    ]
