# Generated by Django 5.1.7 on 2026-06-15 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0006_remove_personajuridica_productor_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personahumana',
            name='cuil_cuit',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='El CUIL/CUIT debe tener exactamente 11 dígitos numéricos, sin guiones ni espacios.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='area_desempeno_JJPP_2',
            field=models.CharField(blank=True, choices=[('Productora', 'Empresa de producción'), ('PostProd', 'Empresa de postproducción'), ('Serv_Prod', 'Empresa de servicios para la producción'), ('PPJJ_Espec', 'Persona jurídica específica audiovisual'), ('PPJJ_Cult', 'Persona jurídica cultural'), ('otro', 'Otro')], default='', max_length=50, verbose_name='Área de desempeño secundaria'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='cuil_cuit',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='El CUIL/CUIT debe tener exactamente 11 dígitos numéricos, sin guiones ni espacios.', regex='^\\d{11}$')]),
        ),
    ]
