# Generated by Django 5.1.7 on 2025-12-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0006_alter_personahumana_link_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personahumana',
            name='actividad_dgr',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('PF', '591110 - Producción de filmes y videocintas'), ('PPF', '591120 - Postproducción de filmes y videocintas'), ('O', 'Otra'), ('N', 'Ninguna')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='actividad_dgr',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('PF', '591110 - Producción de filmes y videocintas'), ('PPF', '591120 - Postproducción de filmes y videocintas'), ('O', 'Otra'), ('N', 'Ninguna')], default='', max_length=50),
        ),
    ]
