# Generated by Django 5.1.7 on 2025-12-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0007_alter_personahumana_actividad_dgr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personahumana',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='lugar_residencia',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EP', 'El Potrero'), ('EQ', 'El Quebrachal'), ('ET', 'El Tala'), ('Em', 'Embarcación'), ('GG', 'General Güemes'), ('GP', 'General Pizzarro'), ('GM', 'General Mosconi'), ('GB', 'General Ballivián'), ('Gu', 'Guachipas'), ('HI', 'Hipólito Yrigoyen'), ('Ir', 'Iruya'), ('IC', 'Isla de Cañas'), ('JVG', 'Joaquín V. Gonzalez'), ('LC', 'La Caldera'), ('LCa', 'La Candelaria'), ('LM', 'La Merced'), ('LP', 'La Poma'), ('LV', 'La Viña'), ('LL', 'Las Lajitas'), ('LT', 'Los Toldos'), ('Mo', 'Molinos'), ('Na', 'Nazareno'), ('Pa', 'Payogasta'), ('PSM', 'Profesor Salvador Mazza'), ('RP', 'Río Piedras'), ('RBN', 'Rivadavia Banda Norte'), ('RBS', 'Rivadavia Banda Sur'), ('SAC', 'San Antonio de los Cobres'), ('SC', 'San Carlos'), ('SJM', 'San José de Metán'), ('SL', 'San Lorenzo'), ('Or', 'San Ramón de la Nueva Orán'), ('SVE', 'Santa Victoria Este'), ('SVO', 'Santa Victoria Oeste'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('TG', 'Tolar Grande'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='lugar_residencia',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EP', 'El Potrero'), ('EQ', 'El Quebrachal'), ('ET', 'El Tala'), ('Em', 'Embarcación'), ('GG', 'General Güemes'), ('GP', 'General Pizzarro'), ('GM', 'General Mosconi'), ('GB', 'General Ballivián'), ('Gu', 'Guachipas'), ('HI', 'Hipólito Yrigoyen'), ('Ir', 'Iruya'), ('IC', 'Isla de Cañas'), ('JVG', 'Joaquín V. Gonzalez'), ('LC', 'La Caldera'), ('LCa', 'La Candelaria'), ('LM', 'La Merced'), ('LP', 'La Poma'), ('LV', 'La Viña'), ('LL', 'Las Lajitas'), ('LT', 'Los Toldos'), ('Mo', 'Molinos'), ('Na', 'Nazareno'), ('Pa', 'Payogasta'), ('PSM', 'Profesor Salvador Mazza'), ('RP', 'Río Piedras'), ('RBN', 'Rivadavia Banda Norte'), ('RBS', 'Rivadavia Banda Sur'), ('SAC', 'San Antonio de los Cobres'), ('SC', 'San Carlos'), ('SJM', 'San José de Metán'), ('SL', 'San Lorenzo'), ('Or', 'San Ramón de la Nueva Orán'), ('SVE', 'Santa Victoria Este'), ('SVO', 'Santa Victoria Oeste'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('TG', 'Tolar Grande'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], default='', max_length=100),
        ),
    ]
