# Generated by Django 5.1.7 on 2026-07-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0008_nombre_apellido_edad_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personahumana',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido/s'),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre/s'),
        ),
    ]
