# Generated by Django 5.1.7 on 2025-12-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0009_personahumana_codigo_postal_fiscal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personahumana',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='personajuridica',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='personajuridica',
            name='lugar_residencia',
        ),
        migrations.RemoveField(
            model_name='personajuridica',
            name='otro_lugar_residencia',
        ),
        migrations.AddField(
            model_name='personahumana',
            name='codigo_postal_real',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='codigo_postal_fiscal',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='localidad_fiscal',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EP', 'El Potrero'), ('EQ', 'El Quebrachal'), ('ET', 'El Tala'), ('Em', 'Embarcación'), ('GG', 'General Güemes'), ('GP', 'General Pizzarro'), ('GM', 'General Mosconi'), ('GB', 'General Ballivián'), ('Gu', 'Guachipas'), ('HI', 'Hipólito Yrigoyen'), ('Ir', 'Iruya'), ('IC', 'Isla de Cañas'), ('JVG', 'Joaquín V. Gonzalez'), ('LC', 'La Caldera'), ('LCa', 'La Candelaria'), ('LM', 'La Merced'), ('LP', 'La Poma'), ('LV', 'La Viña'), ('LL', 'Las Lajitas'), ('LT', 'Los Toldos'), ('Mo', 'Molinos'), ('Na', 'Nazareno'), ('Pa', 'Payogasta'), ('PSM', 'Profesor Salvador Mazza'), ('RP', 'Río Piedras'), ('RBN', 'Rivadavia Banda Norte'), ('RBS', 'Rivadavia Banda Sur'), ('SAC', 'San Antonio de los Cobres'), ('SC', 'San Carlos'), ('SJM', 'San José de Metán'), ('SL', 'San Lorenzo'), ('Or', 'San Ramón de la Nueva Orán'), ('SVE', 'Santa Victoria Este'), ('SVO', 'Santa Victoria Oeste'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('TG', 'Tolar Grande'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='actividad_dgr',
            field=models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('PF', '591110 - Producción de filmes y videocintas'), ('PPF', '591120 - Postproducción de filmes y videocintas'), ('O', 'Otra'), ('N', 'Ninguna')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='area_desempeno_1',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('Productor', 'Productor/a'), ('Jefe_prod', 'Jefe/a de producción'), ('Asist_prod', 'Asistente de producción'), ('Jefe_loc', 'Jefe/a de locaciones'), ('Director', 'Director/a'), ('Asist_Dir', 'Asistente de dirección'), ('Dir_Cast', 'Director/a de casting'), ('Dir_Foto', 'Director/a de fotografía'), ('Camara', 'Camarógrafo/a'), ('Key_Grip', 'Key Grip'), ('Video Asist_DIT', 'Video Asist / DIT<'), ('Gaffer', 'Gaffer'), ('Guionista', 'Guionista'), ('Reflec', 'Reflectorista'), ('Dir_Arte', 'Dirección de Arte'), ('Escnog', 'Escenógrafo/a'), ('Vest', 'Vestuarista'), ('Maqui', 'Jefe/a de Maquillaje'), ('Dir_Son', 'Dirección de Sonido'), ('Ayu_Son', 'Ayudante de Sonido '), ('Dir_Son_Post', 'Dirección de Sonido Post / Mezclador/a'), ('Post_Prod', 'Postproductor/a'), ('Editor', 'Editor/a'), ('Color', 'Colorista'), ('Animam', 'Animador/a'), ('Realizador', 'Realizador/a integral'), ('Game_Design', 'Game Designer'), ('Game_Artist', 'Game Artist'), ('otro', 'Otro')], max_length=50, verbose_name='Área de desempeño principal'),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='area_desempeno_2',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('Productor', 'Productor/a'), ('Jefe_prod', 'Jefe/a de producción'), ('Asist_prod', 'Asistente de producción'), ('Jefe_loc', 'Jefe/a de locaciones'), ('Director', 'Director/a'), ('Asist_Dir', 'Asistente de dirección'), ('Dir_Cast', 'Director/a de casting'), ('Dir_Foto', 'Director/a de fotografía'), ('Camara', 'Camarógrafo/a'), ('Key_Grip', 'Key Grip'), ('Video Asist_DIT', 'Video Asist / DIT<'), ('Gaffer', 'Gaffer'), ('Guionista', 'Guionista'), ('Reflec', 'Reflectorista'), ('Dir_Arte', 'Dirección de Arte'), ('Escnog', 'Escenógrafo/a'), ('Vest', 'Vestuarista'), ('Maqui', 'Jefe/a de Maquillaje'), ('Dir_Son', 'Dirección de Sonido'), ('Ayu_Son', 'Ayudante de Sonido '), ('Dir_Son_Post', 'Dirección de Sonido Post / Mezclador/a'), ('Post_Prod', 'Postproductor/a'), ('Editor', 'Editor/a'), ('Color', 'Colorista'), ('Animam', 'Animador/a'), ('Realizador', 'Realizador/a integral'), ('Game_Design', 'Game Designer'), ('Game_Artist', 'Game Artist'), ('otro', 'Otro')], max_length=50, verbose_name='Área de desempeño secundaria'),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='genero',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('O', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='localidad_fiscal',
            field=models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EP', 'El Potrero'), ('EQ', 'El Quebrachal'), ('ET', 'El Tala'), ('Em', 'Embarcación'), ('GG', 'General Güemes'), ('GP', 'General Pizzarro'), ('GM', 'General Mosconi'), ('GB', 'General Ballivián'), ('Gu', 'Guachipas'), ('HI', 'Hipólito Yrigoyen'), ('Ir', 'Iruya'), ('IC', 'Isla de Cañas'), ('JVG', 'Joaquín V. Gonzalez'), ('LC', 'La Caldera'), ('LCa', 'La Candelaria'), ('LM', 'La Merced'), ('LP', 'La Poma'), ('LV', 'La Viña'), ('LL', 'Las Lajitas'), ('LT', 'Los Toldos'), ('Mo', 'Molinos'), ('Na', 'Nazareno'), ('Pa', 'Payogasta'), ('PSM', 'Profesor Salvador Mazza'), ('RP', 'Río Piedras'), ('RBN', 'Rivadavia Banda Norte'), ('RBS', 'Rivadavia Banda Sur'), ('SAC', 'San Antonio de los Cobres'), ('SC', 'San Carlos'), ('SJM', 'San José de Metán'), ('SL', 'San Lorenzo'), ('Or', 'San Ramón de la Nueva Orán'), ('SVE', 'Santa Victoria Este'), ('SVO', 'Santa Victoria Oeste'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('TG', 'Tolar Grande'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='lugar_residencia',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EP', 'El Potrero'), ('EQ', 'El Quebrachal'), ('ET', 'El Tala'), ('Em', 'Embarcación'), ('GG', 'General Güemes'), ('GP', 'General Pizzarro'), ('GM', 'General Mosconi'), ('GB', 'General Ballivián'), ('Gu', 'Guachipas'), ('HI', 'Hipólito Yrigoyen'), ('Ir', 'Iruya'), ('IC', 'Isla de Cañas'), ('JVG', 'Joaquín V. Gonzalez'), ('LC', 'La Caldera'), ('LCa', 'La Candelaria'), ('LM', 'La Merced'), ('LP', 'La Poma'), ('LV', 'La Viña'), ('LL', 'Las Lajitas'), ('LT', 'Los Toldos'), ('Mo', 'Molinos'), ('Na', 'Nazareno'), ('Pa', 'Payogasta'), ('PSM', 'Profesor Salvador Mazza'), ('RP', 'Río Piedras'), ('RBN', 'Rivadavia Banda Norte'), ('RBS', 'Rivadavia Banda Sur'), ('SAC', 'San Antonio de los Cobres'), ('SC', 'San Carlos'), ('SJM', 'San José de Metán'), ('SL', 'San Lorenzo'), ('Or', 'San Ramón de la Nueva Orán'), ('SVE', 'Santa Victoria Este'), ('SVO', 'Santa Victoria Oeste'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('TG', 'Tolar Grande'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='nivel_educativo',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('Pc', 'Primario completo'), ('Sc', 'Secundario completo'), ('Tc', 'Terciario completo'), ('Uc', 'Universitario completo'), ('Pos', 'Posgrado completo')], max_length=50, verbose_name='Nivel educativo alcanzado'),
        ),
        migrations.AlterField(
            model_name='personahumana',
            name='situacion_iva',
            field=models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('N', 'Ninguna'), ('EX', 'Exento'), ('M', 'Monotributista'), ('RI', 'Responsable Inscripto'), ('O', 'Otra')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='actividad_dgr',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('PF', '591110 - Producción de filmes y videocintas'), ('PPF', '591120 - Postproducción de filmes y videocintas'), ('O', 'Otra'), ('N', 'Ninguna')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='area_desempeno_JJPP_1',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('', '- Empresas -'), ('Productora', 'Empresa de producción'), ('PostProd', 'Empresa de postproducción'), ('Serv_Prod', 'Empresa de servicios para la producción'), ('', '- Personas Jurídicas s/fines de lucro -'), ('PPJJ_Espec', 'Específica Audiovisual '), ('PPJJ_Cult', 'Cultural'), ('otro', 'Otro')], max_length=50, verbose_name='Área de desempeño principal'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='area_desempeno_JJPP_2',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('', '- Empresas -'), ('Productora', 'Empresa de producción'), ('PostProd', 'Empresa de postproducción'), ('Serv_Prod', 'Empresa de servicios para la producción'), ('', '- Personas Jurídicas s/fines de lucro -'), ('PPJJ_Espec', 'Específica Audiovisual '), ('PPJJ_Cult', 'Cultural'), ('otro', 'Otro')], max_length=50, verbose_name='Área de desempeño secundaria'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='situacion_iva',
            field=models.CharField(choices=[('', '- Seleccionar -'), ('N', 'Ninguna'), ('EX', 'Exento'), ('M', 'Monotributista'), ('RI', 'Responsable Inscripto'), ('O', 'Otra')], max_length=5),
        ),
    ]
