# Generated by Django 5.1.7 on 2025-12-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0010_remove_personahumana_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personahumana',
            name='area_desempeno_2',
            field=models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('Productor', 'Productor/a'), ('Jefe_prod', 'Jefe/a de producción'), ('Asist_prod', 'Asistente de producción'), ('Jefe_loc', 'Jefe/a de locaciones'), ('Director', 'Director/a'), ('Asist_Dir', 'Asistente de dirección'), ('Dir_Cast', 'Director/a de casting'), ('Dir_Foto', 'Director/a de fotografía'), ('Camara', 'Camarógrafo/a'), ('Key_Grip', 'Key Grip'), ('Video Asist_DIT', 'Video Asist / DIT<'), ('Gaffer', 'Gaffer'), ('Guionista', 'Guionista'), ('Reflec', 'Reflectorista'), ('Dir_Arte', 'Dirección de Arte'), ('Escnog', 'Escenógrafo/a'), ('Vest', 'Vestuarista'), ('Maqui', 'Jefe/a de Maquillaje'), ('Dir_Son', 'Dirección de Sonido'), ('Ayu_Son', 'Ayudante de Sonido '), ('Dir_Son_Post', 'Dirección de Sonido Post / Mezclador/a'), ('Post_Prod', 'Postproductor/a'), ('Editor', 'Editor/a'), ('Color', 'Colorista'), ('Animam', 'Animador/a'), ('Realizador', 'Realizador/a integral'), ('Game_Design', 'Game Designer'), ('Game_Artist', 'Game Artist'), ('otro', 'Otro')], max_length=50, null=True, verbose_name='Área de desempeño secundaria'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='link_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='link_3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
