# Generated by Django 5.1.7 on 2025-12-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0011_alter_personahumana_area_desempeno_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personahumana',
            name='link_1',
        ),
        migrations.RemoveField(
            model_name='personahumana',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='personahumana',
            name='link_3',
        ),
        migrations.RemoveField(
            model_name='personajuridica',
            name='link_1',
        ),
        migrations.RemoveField(
            model_name='personajuridica',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='personajuridica',
            name='link_3',
        ),
        migrations.AddField(
            model_name='personahumana',
            name='canal_video',
            field=models.URLField(blank=True, help_text='Canal de YouTube, Vimeo u otra plataforma de video', null=True, verbose_name='Canal audiovisual'),
        ),
        migrations.AddField(
            model_name='personahumana',
            name='instagram',
            field=models.URLField(blank=True, help_text='Perfil de Instagram profesional', null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='personahumana',
            name='link_trabajo_destacado',
            field=models.URLField(blank=True, help_text='Link a una obra o trabajo audiovisual relevante', null=True, verbose_name='Trabajo destacado'),
        ),
        migrations.AddField(
            model_name='personahumana',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Perfil de LinkedIn', null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='personahumana',
            name='portfolio_web',
            field=models.URLField(blank=True, help_text='Sitio web personal, de la productora o portfolio online (Vimeo, Behance, etc.)', null=True, verbose_name='Sitio web / Portfolio'),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='canal_video',
            field=models.URLField(blank=True, help_text='Canal de YouTube, Vimeo u otra plataforma de video', null=True, verbose_name='Canal audiovisual'),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='instagram',
            field=models.URLField(blank=True, help_text='Perfil de Instagram profesional', null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='link_trabajo_destacado',
            field=models.URLField(blank=True, help_text='Link a una obra o trabajo audiovisual relevante', null=True, verbose_name='Trabajo destacado'),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Perfil de LinkedIn', null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='portfolio_web',
            field=models.URLField(blank=True, help_text='Sitio web personal, de la productora o portfolio online (Vimeo, Behance, etc.)', null=True, verbose_name='Sitio web / Portfolio'),
        ),
    ]
