# Generated by Django 5.1.7 on 2026-01-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro_audiovisual", "0012_remove_personahumana_link_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personahumana",
            name="actividad_dgr",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "- Seleccionar -"),
                    ("591110", "591110 - Producción de filmes y videocintas"),
                    ("591120", "591120 - Postproducción de filmes y videocintas"),
                    ("O", "Otra"),
                    ("N", "Ninguna"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personahumana",
            name="area_cultural",
            field=models.CharField(
                choices=[
                    ("", "- Seleccionar -"),
                    ("Actor", "Actror / Actríz"),
                    ("musica", "Música"),
                    ("danza", "Danza"),
                    ("literatura", "Literatura"),
                    ("visuales", "Artes Visuales"),
                    ("comunicacion", "Comunicación"),
                    ("locutor", "Locutor/a"),
                    ("educacion", "Educación"),
                    ("ninguna", "Ninguna"),
                    ("otro", "Otro"),
                ],
                max_length=50,
                verbose_name="Área cultural complementaria",
            ),
        ),
        migrations.AlterField(
            model_name="personahumana",
            name="canal_video",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Canal de YouTube, Vimeo u otra plataforma de video",
                max_length=300,
                verbose_name="Canal audiovisual",
            ),
        ),
        migrations.AlterField(
            model_name="personahumana",
            name="instagram",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Perfil de Instagram profesional",
                max_length=300,
                verbose_name="Instagram",
            ),
        ),
        migrations.AlterField(
            model_name="personahumana",
            name="link_trabajo_destacado",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Link a una obra o trabajo audiovisual relevante",
                max_length=300,
                verbose_name="Trabajo destacado",
            ),
        ),
        migrations.AlterField(
            model_name="personahumana",
            name="linkedin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Perfil de LinkedIn",
                max_length=300,
                verbose_name="LinkedIn",
            ),
        ),
        migrations.AlterField(
            model_name="personahumana",
            name="portfolio_web",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Sitio web personal, de la productora o portfolio online (Vimeo, Behance, etc.)",
                max_length=300,
                verbose_name="Sitio web / Portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="personajuridica",
            name="actividad_dgr",
            field=models.CharField(
                choices=[
                    ("", "- Seleccionar -"),
                    ("591110", "591110 - Producción de filmes y videocintas"),
                    ("591120", "591120 - Postproducción de filmes y videocintas"),
                    ("O", "Otra"),
                    ("N", "Ninguna"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="personajuridica",
            name="canal_video",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Canal de YouTube, Vimeo u otra plataforma de video",
                max_length=300,
                verbose_name="Canal audiovisual",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personajuridica",
            name="instagram",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Perfil de Instagram profesional",
                max_length=300,
                verbose_name="Instagram",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personajuridica",
            name="link_trabajo_destacado",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Link a una obra o trabajo audiovisual relevante",
                max_length=300,
                verbose_name="Trabajo destacado",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personajuridica",
            name="linkedin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Perfil de LinkedIn",
                max_length=300,
                verbose_name="LinkedIn",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personajuridica",
            name="portfolio_web",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Sitio web personal, de la productora o portfolio online (Vimeo, Behance, etc.)",
                max_length=300,
                verbose_name="Sitio web / Portfolio",
            ),
            preserve_default=False,
        ),
    ]
