# Generated by Django 5.1.7 on 2026-01-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_audiovisual', '0013_alter_personahumana_actividad_dgr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajuridica',
            name='canal_video',
            field=models.CharField(blank=True, default='', help_text='Canal de YouTube, Vimeo u otra plataforma de video', max_length=300, verbose_name='Canal audiovisual'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='instagram',
            field=models.CharField(blank=True, default='', help_text='Perfil de Instagram profesional', max_length=300, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='link_trabajo_destacado',
            field=models.CharField(blank=True, default='', help_text='Link a una obra o trabajo audiovisual relevante', max_length=300, verbose_name='Trabajo destacado'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='linkedin',
            field=models.CharField(blank=True, default='', help_text='Perfil de LinkedIn', max_length=300, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='portfolio_web',
            field=models.CharField(blank=True, default='', help_text='Sitio web personal, de la productora o portfolio online (Vimeo, Behance, etc.)', max_length=300, verbose_name='Sitio web / Portfolio'),
        ),
    ]
