# Generated by Django 5.1.7 on 2026-04-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcion',
            options={'ordering': ['orden']},
        ),
    ]
