# Generated by Django 5.1.7 on 2026-04-03 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_opcion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabraClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('nodo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.nodo')),
            ],
            options={
                'verbose_name': 'Palabra clave',
                'verbose_name_plural': 'Palabras clave',
                'ordering': ['texto'],
            },
        ),
    ]
