# Generated by Django 5.1.7 on 2026-04-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_palabraclave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='palabraclave',
            name='nodo_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabras_clave', to='chatbot.nodo'),
        ),
    ]
