# Generated by Django 5.1.7 on 2026-04-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_nodo_options_alter_palabraclave_nodo_destino'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palabraclave',
            options={'ordering': ['-prioridad', 'texto'], 'verbose_name': 'Palabra clave', 'verbose_name_plural': 'Palabras clave'},
        ),
        migrations.AddField(
            model_name='palabraclave',
            name='prioridad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
