# Generated by Django 5.1.7 on 2026-06-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_palabraclave_options_palabraclave_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_no_encontrado', models.TextField(default='No estoy seguro de haber entendido. Podés reformular la consulta o elegir una de las opciones disponibles.', help_text='Se muestra cuando ninguna palabra clave coincide con la consulta del usuario.', verbose_name='Mensaje cuando no se encuentra respuesta')),
            ],
            options={
                'verbose_name': 'Configuración del chatbot',
                'verbose_name_plural': 'Configuración del chatbot',
            },
        ),
        migrations.CreateModel(
            name='ConsultaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_consulta', models.CharField(max_length=500)),
                ('keyword_matcheada', models.CharField(blank=True, max_length=100, null=True)),
                ('encontrado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nodo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_log', to='chatbot.nodo')),
            ],
            options={
                'verbose_name': 'Consulta registrada',
                'verbose_name_plural': 'Consultas registradas',
                'ordering': ['-fecha'],
            },
        ),
    ]
