# Generated by Django 5.1.7 on 2026-01-18 18:36

import convocatorias.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro_audiovisual', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='convocatorias/archivos/', validators=[convocatorias.validators.validar_pdf, convocatorias.validators.validar_tamano_archivo], verbose_name='Archivo del proyecto (PDF)')),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion_corta', models.TextField(blank=True)),
                ('descripcion_larga', models.TextField(blank=True)),
                ('url_curso', models.URLField(blank=True, help_text='Solo completar si el curso es asincrónico.', null=True, verbose_name='URL del curso asincrónico')),
                ('categoria', models.CharField(choices=[('CONCURSO', 'Concurso'), ('PROGRAMA', 'Programa'), ('SUBSIDIO', 'Subsidio'), ('CURSO', 'Curso / Capacitación'), ('INCENTIVO', 'Incentivo'), ('BENEFICIO', 'Beneficio')], max_length=20)),
                ('tematica_genero', models.CharField(blank=True, max_length=200)),
                ('linea', models.CharField(choices=[('fomento', 'Fomento'), ('beneficio', 'Beneficio'), ('formacion', 'Formación'), ('incentivo', 'Incentivo'), ('libre', 'Libre')], max_length=20)),
                ('requisitos', models.TextField(blank=True)),
                ('beneficios', models.TextField(blank=True)),
                ('bases_pdf', models.FileField(blank=True, null=True, upload_to='convocatorias/bases/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='convocatorias/img/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('bloque_personas', models.CharField(choices=[('JURADO', 'Jurado'), ('FORMADORES', 'Formadores'), ('TUTORES', 'Tutores'), ('NINGUNO', 'Sin título')], default='JURADO', max_length=20)),
                ('jurado1_nombre', models.CharField(blank=True, max_length=200)),
                ('jurado1_foto', models.ImageField(blank=True, null=True, upload_to='convocatorias/jurados/')),
                ('jurado1_bio', models.TextField(blank=True)),
                ('jurado2_nombre', models.CharField(blank=True, max_length=200)),
                ('jurado2_foto', models.ImageField(blank=True, null=True, upload_to='convocatorias/jurados/')),
                ('jurado2_bio', models.TextField(blank=True)),
                ('jurado3_nombre', models.CharField(blank=True, max_length=200)),
                ('jurado3_foto', models.ImageField(blank=True, null=True, upload_to='convocatorias/jurados/')),
                ('jurado3_bio', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('url_destino', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['orden', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='convocatorias/jurados/')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_proyecto', models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('', '- Cine -'), ('cine_corto', 'Cortometraje'), ('cine_largo', 'Largometraje'), ('', '- Serie -'), ('serie', 'Serie'), ('serie_web', 'Serie Web'), ('', '- Animacion -'), ('corto_animacion', 'Cortometraje animación'), ('largo_animacion', 'Largoometraje animación'), ('serie_animacion', 'Serie animación'), ('serieweb_animacion', 'Serie web animación'), ('videoclip_animacion', 'Videoclip animación'), ('', '- Otros -'), ('tv', 'TV'), ('publicidad', 'Publicidad'), ('videoclip', 'Videoclip'), ('videojuego', 'Videojuego'), ('transmedia', 'Transmedia'), ('otro', 'Otro')], max_length=50)),
                ('genero', models.CharField(blank=True, choices=[('ficcion', 'Ficción'), ('documental', 'Documental'), ('noficcion', 'No ficción'), ('educativo', 'Educativo'), ('deportivo', 'Deportivo'), ('simulacion', 'Simulacion'), ('ludico', 'Lúdico'), ('otro', 'Otro')], max_length=50)),
                ('declaracion_jurada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('revision_admin', 'En revisión administrativa'), ('observado', 'Observado (requiere subsanación)'), ('admitido', 'Admitido'), ('evaluacion_jurado', 'En evaluación por jurado'), ('seleccionado', 'Seleccionado'), ('no_seleccionado', 'No seleccionado'), ('finalizado', 'Finalizado')], default='borrador', max_length=30)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ObservacionAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('PERSONAL', 'Documentación personal'), ('PROYECTO', 'Documentación del proyecto')], help_text='Tipo de documentación a subsanar', max_length=20)),
                ('descripcion', models.CharField(help_text='Ej: Falta DNI, Falta CBU, Presupuesto sin firma', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('subsanada', models.BooleanField(default=False)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='convocatorias.postulacion')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERSONAL', 'Documentación personal'), ('PROYECTO', 'Documentación del proyecto'), ('SUBSANADO', 'Documentación subsanada')], max_length=20)),
                ('subtipo_subsanado', models.CharField(blank=True, choices=[('PROYECTO', 'Subsanación de proyecto'), ('ADMIN', 'Subsanación administrativa')], db_index=True, help_text='Solo se usa cuando el tipo es SUBSANADO', max_length=20, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADO', 'Enviado')], db_index=True, default='PENDIENTE', max_length=10)),
                ('archivo', models.FileField(upload_to='postulaciones/documentos/', validators=[convocatorias.validators.validar_pdf, convocatorias.validators.validar_tamano_archivo])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='convocatorias.postulacion')),
            ],
        ),
        migrations.CreateModel(
            name='Rendicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_documentacion', models.URLField(blank=True)),
                ('observaciones_usuario', models.TextField(blank=True)),
                ('observaciones_admin', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('OBSERVADO', 'Observado'), ('SUBSANADO', 'Subsanado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('fisico_estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20)),
                ('fisico_fecha_recepcion', models.DateField(blank=True, null=True)),
                ('fisico_observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_revision', models.DateTimeField(blank=True, null=True)),
                ('historial', models.JSONField(blank=True, default=list)),
                ('postulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rendicion', to='convocatorias.postulacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionJuradoConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('jurado', models.ForeignKey(limit_choices_to={'groups__name': 'jurado'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Jurado')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria', verbose_name='Convocatoria asignada')),
            ],
            options={
                'verbose_name': 'Asignación de jurado a convocatoria',
                'verbose_name_plural': 'Asignaciones de jurados a convocatorias',
                'unique_together': {('jurado', 'convocatoria')},
            },
        ),
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('user', 'convocatoria')},
            },
        ),
        migrations.CreateModel(
            name='InscripcionFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('apellido', models.CharField(blank=True, max_length=120)),
                ('dni', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=60)),
                ('localidad', models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EM', 'El Molinar'), ('ET', 'El Tala'), ('Gi', 'General Güemes'), ('GM', 'General Mosconi'), ('Ga', 'Gaona'), ('Gp', 'Guachipas'), ('Hi', 'Hipólito Yrigoyen'), ('I', 'Iruya'), ('JV', 'Joaquín V. González'), ('LL', 'La Caldera'), ('LC', 'La Candelaria'), ('LV', 'La Viña'), ('LM', 'Las Lajitas'), ('LS', 'Los Toldos'), ('LR', 'Rosario de Lerma'), ('LP', 'La Poma'), ('LQ', 'La Quesera'), ('MA', 'Metán'), ('Mi', 'Molinos'), ('NP', 'Nazareno'), ('OC', 'Orán'), ('Pa', 'Payogasta'), ('Pi', 'Pichanal'), ('Po', 'Posadas'), ('Ri', 'Rivadavia'), ('RN', 'Rosario de la Frontera'), ('RS', 'Rosario de Santa Fe'), ('SA', 'San Antonio de los Cobres'), ('SL', 'San Carlos'), ('SO', 'San Lorenzo'), ('SP', 'San Ramón de la Nueva Orán'), ('ST', 'Santa Victoria Este'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('To', 'Tolombón'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], max_length=20)),
                ('otra_localidad', models.CharField(blank=True, max_length=120)),
                ('vinculo_sector', models.CharField(blank=True, choices=[('sector', 'Trabajo actualmente en el sector audiovisual'), ('empezando', 'Estoy empezando / quiero insertarme'), ('no_sector', 'No, pero quiero capacitarme')], max_length=20)),
                ('declaracion_jurada', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('inscripto', 'Inscripto'), ('admitido', 'Admitido'), ('no_admitido', 'No admitido'), ('lista_espera', 'Lista de espera')], default='inscripto', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria')),
                ('persona_humana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_audiovisual.personahumana')),
                ('persona_juridica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_audiovisual.personajuridica')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción a formación',
                'verbose_name_plural': 'Inscripciones a formación',
                'ordering': ['-fecha'],
                'unique_together': {('user', 'convocatoria')},
            },
        ),
    ]
