# Generated by Django 5.2.8 on 2025-11-27 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentacion/personal/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostulacionIDEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea_fomento', models.CharField(choices=[('CONC_FICCION', 'Concurso de cortometrajes de ficción'), ('CONC_VIDEOCLIP', 'Concurso de videoclips'), ('PROG_LARGOS', 'Desarrollo de largometrajes'), ('PROG_LAB_CORTOS', 'Laboratorio de cortometrajes'), ('PROG_COMUNIDAD', 'Cine en comunidad'), ('PROG_ANIMACION', 'Entrenamiento en animación'), ('PROG_VIDEOJUEGOS', 'Desarrollo de videojuegos'), ('SUB_RODAJE', 'Apoyo a rodaje'), ('SUB_FINALIZACION', 'Apoyo a finalización de obras'), ('SUB_EVENTOS', 'Apoyo a participación en eventos audiovisuales')], max_length=50)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('tipo_proyecto', models.CharField(choices=[('CORTO', 'Cortometraje'), ('LARGO', 'Largometraje'), ('VIDEOCLIP', 'Videoclip'), ('TRANSMEDIA', 'Transmedia'), ('SERIE', 'Serie'), ('VIDEOJUEGO', 'Videojuego'), ('ANIMACION', 'Animación'), ('COMUNIDAD', 'Cine en comunidad')], max_length=50)),
                ('genero', models.CharField(choices=[('FICCION', 'Ficción'), ('DOCUMENTAL', 'Documental'), ('NO_FICCION', 'No ficción'), ('EDUCATIVO', 'Educativo'), ('DEPORTIVO', 'Deportivo'), ('LUDICO', 'Lúdico'), ('SIMULACION', 'Simulación'), ('OTRO', 'Otro')], max_length=50)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('declaracion_jurada', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('REVISION', 'En revisión'), ('SUBSANAR', 'Subsanar'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='ENVIADA', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentacion/proyecto/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_proyecto', to='convocatorias.postulacionidea')),
            ],
        ),
    ]
