# Generated by Django 5.1.7 on 2025-12-14 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion_corta', models.TextField(blank=True)),
                ('descripcion_larga', models.TextField(blank=True)),
                ('url_curso', models.URLField(blank=True, help_text='Solo completar si el curso es asincrónico.', null=True, verbose_name='URL del curso asincrónico')),
                ('categoria', models.CharField(choices=[('CONCURSO', 'Concurso'), ('PROGRAMA', 'Programa'), ('SUBSIDIO', 'Subsidio'), ('CURSO', 'Curso / Capacitación'), ('INCENTIVO', 'Incentivo'), ('BENEFICIO', 'Beneficio')], max_length=20)),
                ('tematica_genero', models.CharField(blank=True, max_length=200)),
                ('linea', models.CharField(choices=[('fomento', 'Fomento'), ('beneficio', 'Beneficio'), ('formacion', 'Formación'), ('incentivo', 'Incentivo')], max_length=20)),
                ('requisitos', models.TextField(blank=True)),
                ('beneficios', models.TextField(blank=True)),
                ('bases_pdf', models.FileField(blank=True, null=True, upload_to='convocatorias/bases/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='convocatorias/img/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('bloque_personas', models.CharField(choices=[('JURADO', 'Jurado'), ('FORMADORES', 'Formadores'), ('TUTORES', 'Tutores'), ('NINGUNO', 'Sin título')], default='JURADO', max_length=20)),
                ('jurado1_nombre', models.CharField(blank=True, max_length=200)),
                ('jurado1_foto', models.ImageField(blank=True, null=True, upload_to='convocatorias/jurados/')),
                ('jurado1_bio', models.TextField(blank=True)),
                ('jurado2_nombre', models.CharField(blank=True, max_length=200)),
                ('jurado2_foto', models.ImageField(blank=True, null=True, upload_to='convocatorias/jurados/')),
                ('jurado2_bio', models.TextField(blank=True)),
                ('jurado3_nombre', models.CharField(blank=True, max_length=200)),
                ('jurado3_foto', models.ImageField(blank=True, null=True, upload_to='convocatorias/jurados/')),
                ('jurado3_bio', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('url_destino', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['orden', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='convocatorias/jurados/')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('tipo_proyecto', models.CharField(choices=[('CINE', [('cine_corto', 'Cortometraje'), ('cine_largo', 'Largometraje'), ('cine_comunidad', 'Cine en comunidad')]), ('SERIES', [('serie_tv', 'Serie'), ('serie_web', 'Serie Web')]), ('ANIMACION', [('anim_corto', 'Cortometraje de animación'), ('anim_largo', 'Largometraje de animación'), ('anim_serie', 'Serie de animación'), ('anim_serie_web', 'Serie web de animación'), ('anim_videoclip', 'Videoclip de animación')]), ('OTROS', [('videoclip', 'Videoclip'), ('videojuego', 'Videojuego'), ('transmedia', 'Proyecto transmedia')])], max_length=50)),
                ('genero', models.CharField(choices=[('ficcion', 'Ficción'), ('documental', 'Documental'), ('noficcion', 'No ficción'), ('educativo', 'Educativo'), ('deportivo', 'Deportivo'), ('ludico', 'Lúdico'), ('simulacion', 'Simulación'), ('otro', 'Otro')], max_length=50)),
                ('declaracion_jurada', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('REVISION', 'En revisión'), ('SUBSANAR', 'Subsanar'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='ENVIADA', max_length=20)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERSONAL', 'Documentación personal'), ('PROYECTO', 'Documentación del proyecto')], max_length=20)),
                ('archivo', models.FileField(upload_to='postulaciones/documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='convocatorias.postulacion')),
            ],
            options={
                'verbose_name': 'Documento de postulación',
                'verbose_name_plural': 'Documentos de postulación',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('user', 'convocatoria')},
            },
        ),
    ]
