# Generated by Django 5.1.7 on 2025-12-14 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='convocatorias/documentacion_personal/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentacion_personal', to='convocatorias.convocatoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentacion_personal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='convocatorias/documentacion_proyecto/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentacion_proyecto', to='convocatorias.convocatoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentacion_proyecto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
