# Generated by Django 5.2.8 on 2025-12-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
