# Generated by Django 5.1.7 on 2026-02-18 14:59

import convocatorias.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_fix_fecha_creacion_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopostulacion',
            name='archivo',
            field=models.FileField(upload_to='convocatorias/archivos/', validators=[convocatorias.validators.validar_documento_admitido, convocatorias.validators.validar_tamano_archivo], verbose_name='Archivo del proyecto (PDF / Excel / Planilla)'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='bases_pdf',
            field=models.FileField(blank=True, null=True, upload_to='convocatorias/bases/', validators=[convocatorias.validators.validar_documento_admitido, convocatorias.validators.validar_tamano_archivo], verbose_name='Bases (PDF / Excel / Planilla)'),
        ),
        migrations.AlterField(
            model_name='documentopostulacion',
            name='archivo',
            field=models.FileField(upload_to='postulaciones/documentos/', validators=[convocatorias.validators.validar_documento_admitido, convocatorias.validators.validar_tamano_archivo]),
        ),
    ]
