# Generated by Django 5.1.7 on 2025-12-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_documentacionpersonal_documentacionproyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentacionproyecto',
            name='convocatoria',
        ),
        migrations.RemoveField(
            model_name='documentacionproyecto',
            name='user',
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='genero',
            field=models.CharField(choices=[('ficcion', 'Ficción'), ('documental', 'Documental'), ('noficcion', 'No ficción'), ('educativo', 'Educativo'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='tipo_proyecto',
            field=models.CharField(choices=[('cine_corto', 'Cortometraje'), ('cine_largo', 'Largometraje'), ('serie', 'Serie'), ('serie_web', 'Serie Web'), ('animacion', 'Animación'), ('videoclip', 'Videoclip'), ('videojuego', 'Videojuego'), ('transmedia', 'Transmedia'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.DeleteModel(
            name='DocumentacionPersonal',
        ),
        migrations.DeleteModel(
            name='DocumentacionProyecto',
        ),
    ]
