# Generated by Django 5.2.8 on 2025-12-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_alter_convocatoria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatoria',
            name='url_destino',
        ),
    ]
