# Generated by Django 5.1.7 on 2026-06-11 22:51

import convocatorias.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_alter_archivopostulacion_archivo_and_more'),
        ('registro_audiovisual', '0003_alter_personahumana_actividad_dgr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='cbu',
            field=models.CharField(blank=True, help_text='CBU del productor/presentante. Solo requerido si la convocatoria lo exige.', max_length=30, verbose_name='CBU'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='link_pitch',
            field=models.URLField(blank=True, help_text='URL del pitch del proyecto (YouTube, Vimeo, Drive, etc.)', verbose_name='Link al pitch'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='logline',
            field=models.CharField(blank=True, help_text='Máximo 300 caracteres.', max_length=300),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='sinopsis_corta',
            field=models.TextField(blank=True, help_text='Máximo 3000 caracteres.'),
        ),
        migrations.AlterField(
            model_name='documentopostulacion',
            name='tipo',
            field=models.CharField(choices=[('PERSONAL', 'Documentación personal (genérica)'), ('PROYECTO', 'Documentación del proyecto (genérica)'), ('SUBSANADO', 'Documentación subsanada'), ('COMPROBANTE_CBU', 'Comprobante de CBU'), ('DOSSIER', 'Dossier del proyecto'), ('REGISTRO_DNDA', 'Registro DNDA'), ('AUTORIZACION_DERECHOS', 'Autorización de derechos'), ('DDJJ_FINANCIAMIENTO', 'DDJJ de financiamiento'), ('PRESUPUESTO', 'Presupuesto'), ('CARTA_INTENCION', 'Carta de intención'), ('CONSTANCIA_INVITACION', 'Constancia de invitación/participación')], max_length=30),
        ),
        migrations.CreateModel(
            name='ConfiguracionPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiere_director', models.BooleanField(default=False)),
                ('requiere_guionista', models.BooleanField(default=False)),
                ('requiere_realizador', models.BooleanField(default=False)),
                ('requiere_cbu', models.BooleanField(default=True, help_text='CBU del productor/presentante')),
                ('requiere_logline', models.BooleanField(default=False)),
                ('requiere_sinopsis', models.BooleanField(default=False)),
                ('requiere_link_pitch', models.BooleanField(default=False)),
                ('requiere_dossier', models.BooleanField(default=False)),
                ('requiere_dnda', models.BooleanField(default=False)),
                ('requiere_autorizacion_derechos', models.BooleanField(default=False)),
                ('requiere_ddjj_financiamiento', models.BooleanField(default=False)),
                ('requiere_presupuesto', models.BooleanField(default=False)),
                ('requiere_carta_intencion', models.BooleanField(default=False)),
                ('requiere_constancia_invitacion', models.BooleanField(default=False)),
                ('convocatoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='convocatorias.convocatoria')),
            ],
            options={
                'verbose_name': 'Configuración de postulación',
                'verbose_name_plural': 'Configuraciones de postulación',
            },
        ),
        migrations.CreateModel(
            name='IntegrantePostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('PRODUCTOR', 'Productor/a'), ('DIRECTOR', 'Director/a'), ('GUIONISTA', 'Guionista'), ('REALIZADOR', 'Realizador/a integral')], max_length=20)),
                ('nombre_busqueda', models.CharField(blank=True, help_text='Nombre ingresado por el presentante para localizar al integrante en el registro.', max_length=200)),
                ('verificado', models.BooleanField(default=False, help_text='True cuando persona_humana fue encontrada y vinculada en el registro.')),
                ('persona_humana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones_postulacion', to='registro_audiovisual.personahumana')),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='convocatorias.postulacion')),
            ],
            options={
                'verbose_name': 'Integrante del equipo',
                'verbose_name_plural': 'Integrantes del equipo',
                'unique_together': {('postulacion', 'rol')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DNI', 'DNI anverso y reverso'), ('CONSTANCIA_ARCA', 'Constancia de inscripción en ARCA')], max_length=20)),
                ('archivo', models.FileField(upload_to='postulaciones/integrantes/', validators=[convocatorias.validators.validar_documento_admitido, convocatorias.validators.validar_tamano_archivo])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADO', 'Enviado')], default='PENDIENTE', max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='convocatorias.integrantepostulacion')),
            ],
            options={
                'verbose_name': 'Documento de integrante',
                'verbose_name_plural': 'Documentos de integrantes',
                'unique_together': {('integrante', 'tipo')},
            },
        ),
    ]
