# Generated by Django 5.1.7 on 2025-12-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_remove_documentacionproyecto_convocatoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('revision_admin', 'En revisión administrativa'), ('observado', 'Observado (requiere subsanación)'), ('admitido', 'Admitido'), ('evaluacion_jurado', 'En evaluación por jurado'), ('seleccionado', 'Seleccionado'), ('no_seleccionado', 'No seleccionado'), ('finalizado', 'Finalizado')], default='enviado', max_length=30),
        ),
    ]
