# Generated by Django 5.2.8 on 2025-12-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_remove_convocatoria_url_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='convocatorias/jurados/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'ordering': ['orden', '-fecha_inicio']},
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='descripcion_larga',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='url_destino',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='jurados',
            field=models.ManyToManyField(blank=True, to='convocatorias.jurado'),
        ),
    ]
