# Generated by Django 5.1.7 on 2026-06-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0004_postulacion_cbu_postulacion_link_pitch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='requiere_autorizacion_derechos',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='requiere_carta_intencion',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='requiere_constancia_invitacion',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='requiere_ddjj_financiamiento',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='requiere_dnda',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='requiere_dossier',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='requiere_logline',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='requiere_presupuesto',
        ),
        migrations.RemoveField(
            model_name='postulacion',
            name='logline',
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='mostrar_autorizacion_derechos',
            field=models.BooleanField(default=False, verbose_name='Mostrar sección: Autorización de derechos'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='mostrar_carta_intencion',
            field=models.BooleanField(default=False, verbose_name='Mostrar sección: Carta de intención'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='mostrar_constancia_invitacion',
            field=models.BooleanField(default=False, verbose_name='Mostrar sección: Constancia de invitación'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='mostrar_dnda',
            field=models.BooleanField(default=False, verbose_name='Mostrar sección: Registro DNDA'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='mostrar_dossier',
            field=models.BooleanField(default=False, verbose_name='Mostrar sección: Dossier'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='mostrar_guion',
            field=models.BooleanField(default=False, verbose_name='Mostrar sección: Guion'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='mostrar_material_adicional',
            field=models.BooleanField(default=False, verbose_name='Mostrar sección: Material adicional'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='mostrar_nota_intencion',
            field=models.BooleanField(default=False, verbose_name='Mostrar sección: Nota de intención'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='mostrar_planilla_oficial',
            field=models.BooleanField(default=False, verbose_name='Mostrar sección: Planilla oficial'),
        ),
        migrations.AlterField(
            model_name='configuracionpostulacion',
            name='requiere_link_pitch',
            field=models.BooleanField(default=False, verbose_name='Link al pitch'),
        ),
        migrations.AlterField(
            model_name='configuracionpostulacion',
            name='requiere_sinopsis',
            field=models.BooleanField(default=False, verbose_name='Logline / Sinopsis corta'),
        ),
        migrations.AlterField(
            model_name='documentopostulacion',
            name='tipo',
            field=models.CharField(choices=[('PERSONAL', 'Documentación personal (genérica)'), ('PROYECTO', 'Documentación del proyecto (genérica)'), ('SUBSANADO', 'Documentación subsanada'), ('COMPROBANTE_CBU', 'Comprobante de CBU'), ('GUION', 'Guion'), ('DOSSIER', 'Dossier del proyecto'), ('MATERIAL_ADICIONAL', 'Material adicional'), ('PLANILLA_OFICIAL', 'Planilla oficial (presupuesto / plan financiero / equipo / aportes)'), ('REGISTRO_DNDA', 'Registro de la obra en DNDA'), ('AUTORIZACION_DERECHOS', 'Autorización de derechos'), ('NOTA_INTENCION', 'Nota de intención / documentación'), ('CARTA_INTENCION', 'Carta de intención'), ('CONSTANCIA_INVITACION', 'Constancia de invitación/participación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='sinopsis_corta',
            field=models.TextField(blank=True, help_text='Máximo 3000 caracteres.', verbose_name='Logline / Sinopsis corta'),
        ),
    ]
