# Generated by Django 5.2.8 on 2025-12-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0004_jurado_alter_convocatoria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatoria',
            name='jurados',
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='jurado1_foto',
            field=models.ImageField(blank=True, null=True, upload_to='convocatorias/jurados/'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='jurado1_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='jurado2_foto',
            field=models.ImageField(blank=True, null=True, upload_to='convocatorias/jurados/'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='jurado2_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='jurado3_foto',
            field=models.ImageField(blank=True, null=True, upload_to='convocatorias/jurados/'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='jurado3_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='categoria',
            field=models.CharField(choices=[('CONCURSO', 'Concurso'), ('PROGRAMA', 'Programa'), ('SUBSIDIO', 'Subsidio'), ('CURSO', 'Curso'), ('INCENTIVO', 'Incentivo'), ('BENEFICIO', 'Beneficio')], max_length=20),
        ),
    ]
