# Generated by Django 5.1.7 on 2025-12-18 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0004_alter_postulacion_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentopostulacion',
            options={},
        ),
        migrations.AlterField(
            model_name='documentopostulacion',
            name='tipo',
            field=models.CharField(choices=[('PERSONAL', 'Documentación personal'), ('PROYECTO', 'Documentación del proyecto'), ('SUBSANADO', 'Documentación subsanada')], max_length=20),
        ),
        migrations.CreateModel(
            name='ObservacionAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('PERSONAL', 'Documentación personal'), ('PROYECTO', 'Documentación del proyecto')], help_text='Tipo de documentación a subsanar', max_length=20)),
                ('descripcion', models.CharField(help_text='Ej: Falta DNI, Falta CBU, Presupuesto sin firma', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('subsanada', models.BooleanField(default=False)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='convocatorias.postulacion')),
            ],
        ),
    ]
