# Generated by Django 5.2.8 on 2025-12-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0005_remove_convocatoria_jurados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='jurado1_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='jurado2_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='jurado3_bio',
            field=models.TextField(blank=True),
        ),
    ]
