# Generated by Django 5.1.7 on 2026-06-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0005_remove_configuracionpostulacion_requiere_autorizacion_derechos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='presentante',
            field=models.CharField(choices=[('PRODUCTOR', 'Solo el productor/a'), ('PRODUCTOR_O_DIRECTOR', 'Productor/a o director/a (personas distintas)'), ('PUEDEN_COINCIDIR', 'Productor/a y director/a pueden ser la misma persona')], default='PRODUCTOR', max_length=30, verbose_name='¿Quién puede ser presentante?'),
        ),
    ]
