# Generated by Django 5.1.7 on 2025-12-18 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0005_alter_documentopostulacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionJuradoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Debe coincidir con la categoría de la convocatoria (ej: cortometrajes)', max_length=50, verbose_name='Categoría asignada')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('jurado', models.ForeignKey(limit_choices_to={'groups__name': 'jurado'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Jurado')),
            ],
            options={
                'verbose_name': 'Asignación de jurado a categoría',
                'verbose_name_plural': 'Asignaciones de jurados a categorías',
                'unique_together': {('jurado', 'categoria')},
            },
        ),
    ]
