# Generated by Django 5.2.8 on 2025-12-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0006_convocatoria_jurado1_bio_convocatoria_jurado2_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='bloque_personas',
            field=models.CharField(choices=[('JURADO', 'Jurado'), ('FORMACION', 'Formación'), ('NINGUNO', 'Sin título')], default='JURADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='categoria',
            field=models.CharField(choices=[('CONCURSO', 'Concurso'), ('PROGRAMA', 'Programa'), ('SUBSIDIO', 'Subsidio'), ('CURSO', 'Curso / Capacitación'), ('INCENTIVO', 'Incentivo'), ('BENEFICIO', 'Beneficio')], max_length=20),
        ),
    ]
