# Generated by Django 5.1.7 on 2026-06-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0006_config_presentante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='presentante',
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='director_es_presentante',
            field=models.BooleanField(default=False, verbose_name='El director/a puede ser presentante'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='director_puede_ser_productor',
            field=models.BooleanField(default=False, verbose_name='El director/a puede ser también productor/a'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='guionista_puede_ser_director',
            field=models.BooleanField(default=False, verbose_name='El guionista puede ser el director/a'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='guionista_puede_ser_productor',
            field=models.BooleanField(default=False, verbose_name='El guionista puede ser el productor/a'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='productor_es_presentante',
            field=models.BooleanField(default=True, verbose_name='El productor/a puede ser presentante'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='productor_puede_ser_director',
            field=models.BooleanField(default=False, verbose_name='El productor/a puede ser también director/a'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='requiere_productor',
            field=models.BooleanField(default=True, verbose_name='Requiere productor/a'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='tipo_postulante',
            field=models.CharField(choices=[('HUMANA', 'Solo persona humana'), ('JURIDICA', 'Solo persona jurídica'), ('AMBAS', 'Persona humana o jurídica')], default='HUMANA', max_length=10, verbose_name='Tipo de postulante admitido'),
        ),
        migrations.AlterField(
            model_name='configuracionpostulacion',
            name='requiere_cbu',
            field=models.BooleanField(default=True, verbose_name='Requiere CBU'),
        ),
        migrations.AlterField(
            model_name='configuracionpostulacion',
            name='requiere_director',
            field=models.BooleanField(default=False, verbose_name='Requiere director/a'),
        ),
        migrations.AlterField(
            model_name='configuracionpostulacion',
            name='requiere_guionista',
            field=models.BooleanField(default=False, verbose_name='Requiere guionista'),
        ),
        migrations.AlterField(
            model_name='configuracionpostulacion',
            name='requiere_realizador',
            field=models.BooleanField(default=False, verbose_name='Requiere realizador/a'),
        ),
        migrations.AlterField(
            model_name='documentopostulacion',
            name='tipo',
            field=models.CharField(choices=[('PERSONAL', 'Documentación personal (genérica)'), ('PROYECTO', 'Documentación del proyecto (genérica)'), ('SUBSANADO', 'Documentación subsanada'), ('COMPROBANTE_CBU', 'Comprobante de CBU'), ('GUION', 'Guion'), ('DOSSIER', 'Dossier del proyecto'), ('MATERIAL_ADICIONAL', 'Material adicional'), ('PLANILLA_OFICIAL', 'Planilla oficial (presupuesto / plan financiero / equipo / aportes)'), ('REGISTRO_DNDA', 'Registro de la obra en DNDA'), ('AUTORIZACION_DERECHOS', 'Autorización de derechos'), ('NOTA_INTENCION', 'Nota de intención / documentación'), ('CARTA_INTENCION', 'Carta de intención'), ('CONSTANCIA_INVITACION', 'Constancia de invitación/participación'), ('ESTATUTO', 'Estatuto / instrumento constitutivo'), ('CONSTANCIA_ARCA_JUR', 'Constancia ARCA persona jurídica'), ('DNI_REPRESENTANTE', 'DNI del representante legal'), ('DNI_PRODUCTOR_RESP', 'DNI del productor/a responsable'), ('ACTA_AUTORIDADES', 'Acta de designación de autoridades'), ('CONTRATO_COPRODUCTORA', 'Contrato con empresa coproductora')], max_length=30),
        ),
    ]
