# Generated by Django 5.1.7 on 2025-12-18 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0006_asignacionjuradocategoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

