# Generated by Django 5.1.7 on 2025-12-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0007_convocatoria_bloque_personas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='bloque_personas',
            field=models.CharField(choices=[('JURADO', 'Jurado'), ('FORMADORES', 'Formadores'), ('TUTORES', 'Tutores'), ('NINGUNO', 'Sin título')], default='JURADO', max_length=20),
        ),
    ]
