# Generated by Django 5.1.7 on 2026-06-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0007_config_tipo_postulante_y_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='director_es_presentante',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='director_puede_ser_productor',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='guionista_puede_ser_director',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='guionista_puede_ser_productor',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='productor_es_presentante',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='productor_puede_ser_director',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='requiere_productor',
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='director_puede_coincidir',
            field=models.BooleanField(default=False, verbose_name='El/la director/a puede ser la misma persona que el/la productor/a presentante'),
        ),
    ]
