# Generated by Django 5.1.7 on 2025-12-18 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0007_puntajejurado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionJuradoConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria', verbose_name='Convocatoria asignada')),
                ('jurado', models.ForeignKey(limit_choices_to={'groups__name': 'jurado'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Jurado')),
            ],
            options={
                'verbose_name': 'Asignación de jurado a convocatoria',
                'verbose_name_plural': 'Asignaciones de jurados a convocatorias',
                'unique_together': {('jurado', 'convocatoria')},
            },
        ),
        migrations.DeleteModel(
            name='AsignacionJuradoCategoria',
        ),
    ]
