# Generated by Django 5.1.7 on 2025-12-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0008_alter_convocatoria_bloque_personas'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacionidea',
            name='convocatoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria'),
            preserve_default=False,
        ),
    ]
