# Generated by Django 5.1.7 on 2026-01-14 19:44

import convocatorias.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convocatorias", "0008_asignacionjuradoconvocatoria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivoPostulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="convocatorias/archivos/",
                        validators=[
                            convocatorias.validators.validar_pdf,
                            convocatorias.validators.validar_tamano_archivo,
                        ],
                        verbose_name="Archivo del proyecto (PDF)",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="documentopostulacion",
            name="archivo",
            field=models.FileField(
                upload_to="postulaciones/documentos/",
                validators=[
                    convocatorias.validators.validar_pdf,
                    convocatorias.validators.validar_tamano_archivo,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="postulacion",
            name="genero",
            field=models.CharField(
                choices=[
                    ("ficcion", "Ficción"),
                    ("documental", "Documental"),
                    ("noficcion", "No ficción"),
                    ("educativo", "Educativo"),
                    ("deportivo", "Deportivo"),
                    ("simulacion", "Simulacion"),
                    ("ludico", "Lúdico"),
                    ("otro", "Otro"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="postulacion",
            name="tipo_proyecto",
            field=models.CharField(
                choices=[
                    ("", "- Seleccionar -"),
                    ("", "- Cine -"),
                    ("cine_corto", "Cortometraje"),
                    ("cine_largo", "Largometraje"),
                    ("", "- Serie -"),
                    ("serie", "Serie"),
                    ("serie_web", "Serie Web"),
                    ("", "- Animacion -"),
                    ("corto_animacion", "Cortometraje animación"),
                    ("largo_animacion", "Largoometraje animación"),
                    ("serie_animacion", "Serie animación"),
                    ("serieweb_animacion", "Serie web animación"),
                    ("videoclip_animacion", "Videoclip animación"),
                    ("", "- Otros -"),
                    ("tv", "TV"),
                    ("publicidad", "Publicidad"),
                    ("videoclip", "Videoclip"),
                    ("videojuego", "Videojuego"),
                    ("transmedia", "Transmedia"),
                    ("otro", "Otro"),
                ],
                max_length=50,
            ),
        ),
    ]
