# Generated by Django 5.1.7 on 2026-06-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0008_config_simplificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='mostrar_documentacion',
            field=models.BooleanField(default=False, verbose_name='Mostrar sección: Documentación (genérica)'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='linea',
            field=models.CharField(choices=[('fomento', 'Fomento'), ('beneficio', 'Beneficio'), ('formacion', 'Formación'), ('incentivo', 'Incentivo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentopostulacion',
            name='tipo',
            field=models.CharField(choices=[('PERSONAL', 'Documentación personal (genérica)'), ('PROYECTO', 'Documentación del proyecto (genérica)'), ('SUBSANADO', 'Documentación subsanada'), ('COMPROBANTE_CBU', 'Comprobante de CBU'), ('GUION', 'Guion'), ('DOSSIER', 'Dossier del proyecto'), ('MATERIAL_ADICIONAL', 'Material adicional'), ('PLANILLA_OFICIAL', 'Planilla oficial (presupuesto / plan financiero / equipo / aportes)'), ('REGISTRO_DNDA', 'Registro de la obra en DNDA'), ('AUTORIZACION_DERECHOS', 'Autorización de derechos'), ('NOTA_INTENCION', 'Nota de intención / documentación'), ('DOCUMENTACION', 'Documentación'), ('CARTA_INTENCION', 'Carta de intención'), ('CONSTANCIA_INVITACION', 'Constancia de invitación/participación'), ('ESTATUTO', 'Estatuto / instrumento constitutivo'), ('CONSTANCIA_ARCA_JUR', 'Constancia ARCA persona jurídica'), ('DNI_REPRESENTANTE', 'DNI del representante legal'), ('DNI_PRODUCTOR_RESP', 'DNI del productor/a responsable'), ('ACTA_AUTORIDADES', 'Acta de designación de autoridades'), ('CONTRATO_COPRODUCTORA', 'Contrato con empresa coproductora')], max_length=30),
        ),
    ]
