# Generated by Django 5.1.7 on 2025-12-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0009_postulacionidea_convocatoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacionidea',
            name='linea_fomento',
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='linea',
            field=models.CharField(choices=[('fomento', 'Fomento'), ('beneficio', 'Beneficio'), ('formacion', 'Formación'), ('incentivo', 'Incentivo')], default='fomento', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postulacionidea',
            name='genero',
            field=models.CharField(choices=[('ficcion', 'Ficción'), ('documental', 'Documental'), ('noficcion', 'No ficción'), ('educativo', 'Educativo'), ('deportivo', 'Deportivo'), ('ludico', 'Lúdico'), ('simulacion', 'Simulación'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='postulacionidea',
            name='tipo_proyecto',
            field=models.CharField(choices=[('corto', 'Cortometraje'), ('largo', 'Largometraje'), ('videoclip', 'Videoclip'), ('transmedia', 'Transmedia'), ('serie', 'Serie'), ('videojuego', 'Videojuego'), ('animacion', 'Animación'), ('comunidad', 'Cine en comunidad')], max_length=50),
        ),
    ]
