# Generated by Django 5.1.7 on 2026-01-15 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0009_archivopostulacion_and_more'),
        ('registro_audiovisual', '0014_alter_personajuridica_canal_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='linea',
            field=models.CharField(choices=[('fomento', 'Fomento'), ('beneficio', 'Beneficio'), ('formacion', 'Formación'), ('incentivo', 'Incentivo'), ('libre', 'Libre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='genero',
            field=models.CharField(blank=True, choices=[('ficcion', 'Ficción'), ('documental', 'Documental'), ('noficcion', 'No ficción'), ('educativo', 'Educativo'), ('deportivo', 'Deportivo'), ('simulacion', 'Simulacion'), ('ludico', 'Lúdico'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='nombre_proyecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='tipo_proyecto',
            field=models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('', '- Cine -'), ('cine_corto', 'Cortometraje'), ('cine_largo', 'Largometraje'), ('', '- Serie -'), ('serie', 'Serie'), ('serie_web', 'Serie Web'), ('', '- Animacion -'), ('corto_animacion', 'Cortometraje animación'), ('largo_animacion', 'Largoometraje animación'), ('serie_animacion', 'Serie animación'), ('serieweb_animacion', 'Serie web animación'), ('videoclip_animacion', 'Videoclip animación'), ('', '- Otros -'), ('tv', 'TV'), ('publicidad', 'Publicidad'), ('videoclip', 'Videoclip'), ('videojuego', 'Videojuego'), ('transmedia', 'Transmedia'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.CreateModel(
            name='InscripcionFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('apellido', models.CharField(blank=True, max_length=120)),
                ('dni', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=60)),
                ('localidad', models.CharField(blank=True, max_length=120)),
                ('institucion', models.CharField(blank=True, max_length=200)),
                ('vinculo_sector', models.CharField(blank=True, choices=[('sector', 'Trabajo actualmente en el sector audiovisual'), ('empezando', 'Estoy empezando / quiero insertarme'), ('no_sector', 'No, pero quiero capacitarme')], max_length=20)),
                ('motivacion', models.TextField(blank=True)),
                ('declaracion_jurada', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('inscripto', 'Inscripto'), ('admitido', 'Admitido'), ('no_admitido', 'No admitido'), ('lista_espera', 'Lista de espera')], default='inscripto', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria')),
                ('persona_humana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_audiovisual.personahumana')),
                ('persona_juridica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_audiovisual.personajuridica')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción a formación',
                'verbose_name_plural': 'Inscripciones a formación',
                'ordering': ['-fecha'],
                'unique_together': {('user', 'convocatoria')},
            },
        ),
    ]
