# Generated by Django 5.1.7 on 2026-06-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0009_mostrar_documentacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InscripcionFormacion',
        ),
    ]
