# Generated by Django 5.1.7 on 2026-06-12 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0010_drop_inscripcionformacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroJurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='convocatorias/jurados/')),
                ('bio', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Miembro del jurado',
                'verbose_name_plural': 'Miembros del jurado',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Jurado',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='jurado1_bio',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='jurado1_foto',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='jurado1_nombre',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='jurado2_bio',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='jurado2_foto',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='jurado2_nombre',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='jurado3_bio',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='jurado3_foto',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='jurado3_nombre',
        ),
        migrations.AddField(
            model_name='miembrojurado',
            name='convocatoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_jurado', to='convocatorias.convocatoria'),
        ),
    ]
