# Generated by Django 5.1.7 on 2025-12-09 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0010_remove_postulacionidea_linea_fomento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='url_curso',
            field=models.URLField(blank=True, help_text='Solo completar si el curso es asincrónico.', null=True, verbose_name='URL del curso asincrónico'),
        ),
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('user', 'convocatoria')},
            },
        ),
    ]
