# Generated by Django 5.1.7 on 2026-01-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0010_alter_convocatoria_linea_alter_postulacion_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcionformacion',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='inscripcionformacion',
            name='motivacion',
        ),
        migrations.AddField(
            model_name='inscripcionformacion',
            name='otra_localidad',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='inscripcionformacion',
            name='localidad',
            field=models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EM', 'El Molinar'), ('ET', 'El Tala'), ('Gi', 'General Güemes'), ('GM', 'General Mosconi'), ('Ga', 'Gaona'), ('Gp', 'Guachipas'), ('Hi', 'Hipólito Yrigoyen'), ('I', 'Iruya'), ('JV', 'Joaquín V. González'), ('LL', 'La Caldera'), ('LC', 'La Candelaria'), ('LV', 'La Viña'), ('LM', 'Las Lajitas'), ('LS', 'Los Toldos'), ('LR', 'Rosario de Lerma'), ('LP', 'La Poma'), ('LQ', 'La Quesera'), ('MA', 'Metán'), ('Mi', 'Molinos'), ('NP', 'Nazareno'), ('OC', 'Orán'), ('Pa', 'Payogasta'), ('Pi', 'Pichanal'), ('Po', 'Posadas'), ('Ri', 'Rivadavia'), ('RN', 'Rosario de la Frontera'), ('RS', 'Rosario de Santa Fe'), ('SA', 'San Antonio de los Cobres'), ('SL', 'San Carlos'), ('SO', 'San Lorenzo'), ('SP', 'San Ramón de la Nueva Orán'), ('ST', 'Santa Victoria Este'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('To', 'Tolombón'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], max_length=20),
        ),
    ]
