# Generated by Django 5.1.7 on 2026-01-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0011_remove_inscripcionformacion_institucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentopostulacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADO', 'Enviado')], db_index=True, default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='documentopostulacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
