# Generated by Django 5.1.7 on 2026-06-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0011_refactor_miembro_jurado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivoPostulacion',
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='bloque_personas',
            field=models.CharField(choices=[('JURADO', 'Jurado'), ('TUTORES', 'Tutores'), ('NINGUNO', 'Sin título')], default='JURADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='categoria',
            field=models.CharField(choices=[('CONCURSO', 'Concurso'), ('PROGRAMA', 'Programa'), ('SUBSIDIO', 'Subsidio'), ('CURSO', 'Curso / Capacitación')], max_length=20),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='linea',
            field=models.CharField(choices=[('fomento', 'Fomento'), ('cash_rebate', 'Cash Rebate'), ('formacion', 'Formación'), ('exencion', 'Exención impositiva')], max_length=20),
        ),
        migrations.DeleteModel(
            name='InscripcionCurso',
        ),
    ]
