# Generated by Django 5.1.7 on 2025-12-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0011_convocatoria_url_curso_inscripcioncurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacionidea',
            name='duracion_minutos',
        ),
    ]
