# Generated by Django 5.1.7 on 2026-01-17 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0012_documentopostulacion_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_documentacion', models.URLField(blank=True)),
                ('observaciones_usuario', models.TextField(blank=True)),
                ('observaciones_admin', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('OBSERVADO', 'Observado'), ('SUBSANADO', 'Subsanado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('fisico_estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20)),
                ('fisico_fecha_recepcion', models.DateField(blank=True, null=True)),
                ('fisico_observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_revision', models.DateTimeField(blank=True, null=True)),
                ('historial', models.JSONField(blank=True, default=list)),
                ('postulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rendicion', to='convocatorias.postulacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
