# Generated by Django 5.1.7 on 2025-12-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0012_remove_postulacionidea_duracion_minutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacionidea',
            name='tipo_proyecto',
            field=models.CharField(choices=[('CINE', [('cine_corto', 'Cortometraje'), ('cine_largo', 'Largometraje'), ('cine_comunidad', 'Cine en comunidad')]), ('SERIES', [('serie_tv', 'Serie'), ('serie_web', 'Serie Web')]), ('ANIMACION', [('anim_corto', 'Cortometraje de animación'), ('anim_largo', 'Largometraje de animación'), ('anim_serie', 'Serie de animación'), ('anim_serie_web', 'Serie web de animación'), ('anim_videoclip', 'Videoclip de animación')]), ('OTROS', [('videoclip', 'Videoclip'), ('videojuego', 'Videojuego'), ('transmedia', 'Proyecto transmedia')])], max_length=50),
        ),
    ]
