# Generated by Django 5.1.7 on 2026-06-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0012_limpieza_modelos_dead_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='tipo_formacion',
            field=models.CharField(blank=True, choices=[('ASINCRONICA', 'Asincrónica (link público al curso)'), ('INSCRIPCION_LIBRE', 'Inscripción sin registro audiovisual'), ('INSCRIPCION_REGISTRO', 'Inscripción con registro audiovisual')], default='', help_text='Solo para convocatorias de línea Formación.', max_length=25, verbose_name='Tipo de formación'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='categoria',
            field=models.CharField(choices=[('CONCURSO', 'Concurso'), ('PROGRAMA', 'Programa'), ('SUBSIDIO', 'Subsidio'), ('CURSO', 'Curso / Capacitación'), ('BENEFICIO', 'Beneficio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='url_curso',
            field=models.URLField(blank=True, help_text='Completar si el tipo es Asincrónica.', null=True, verbose_name='URL del curso asincrónico'),
        ),
    ]
