# Generated by Django 5.1.7 on 2026-01-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0013_rendicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentopostulacion',
            name='subtipo_subsanado',
            field=models.CharField(blank=True, choices=[('PROYECTO', 'Subsanación de proyecto'), ('ADMIN', 'Subsanación administrativa')], db_index=True, help_text='Solo se usa cuando el tipo es SUBSANADO', max_length=20, null=True),
        ),
    ]
