# Generated by Django 5.1.7 on 2026-06-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0013_tipo_formacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='categoria',
            field=models.CharField(choices=[('CONCURSO', 'Concurso'), ('PROGRAMA', 'Programa'), ('SUBSIDIO', 'Subsidio'), ('CURSO', 'Curso / Capacitación'), ('FORMACION', 'Formación'), ('BENEFICIO', 'Beneficio')], max_length=20),
        ),
    ]
