# Generated by Django 5.1.7 on 2026-06-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0014_config_inscripcion_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='mostrar_formato',
            field=models.BooleanField(default=True, verbose_name='Formato (tipo de proyecto)'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='mostrar_genero',
            field=models.BooleanField(default=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='mostrar_titulo',
            field=models.BooleanField(default=True, verbose_name='Título del proyecto'),
        ),
    ]
