# Generated by Django 5.1.7 on 2026-06-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0015_mostrar_campos_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='requiere_productor_responsable',
            field=models.BooleanField(default=False, verbose_name='Requiere productor/a responsable (persona jurídica)'),
        ),
        migrations.AlterField(
            model_name='documentointegrante',
            name='tipo',
            field=models.CharField(choices=[('DNI', 'DNI anverso y reverso'), ('CONSTANCIA_ARCA', 'Constancia de inscripción en ARCA'), ('CV_BIOFILMOGRAFIA', 'CV / Biofilmografía')], max_length=20),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('revision_admin', 'En revisión administrativa'), ('observado', 'Observado (requiere subsanación)'), ('admitido', 'Admitido'), ('no_admitido', 'No admitido'), ('evaluacion_jurado', 'En evaluación por jurado'), ('seleccionado', 'Seleccionado'), ('no_seleccionado', 'No seleccionado'), ('finalizado', 'Finalizado')], default='borrador', max_length=30),
        ),
    ]
