# Generated by Django 5.1.7 on 2026-06-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0016_configuracionpostulacion_requiere_productor_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatoria',
            name='tipo_formacion',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='url_curso',
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='bloque_personas',
            field=models.CharField(choices=[('JURADO', 'Jurado'), ('FORMADORES', 'Formadores/as'), ('TUTORES', 'Tutores/as'), ('NINGUNO', 'Sin título')], default='JURADO', max_length=20),
        ),
    ]
