# Generated by Django 5.1.7 on 2026-06-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0017_remove_tipo_formacion_url_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionjuradoconvocatoria',
            name='doble_ciego',
            field=models.BooleanField(default=False, help_text='Si está activo, el jurado no ve el equipo de la postulación.', verbose_name='Doble ciego'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='categoria',
            field=models.CharField(choices=[('CONCURSO', 'Concurso'), ('PROGRAMA', 'Programa'), ('SUBSIDIO', 'Subsidio'), ('CURSO', 'Curso / Capacitación'), ('BENEFICIO', 'Beneficio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='linea',
            field=models.CharField(choices=[('fomento', 'Fomento'), ('cash_rebate', 'Cash Rebate'), ('exencion', 'Exención impositiva')], max_length=20),
        ),
        migrations.AlterField(
            model_name='observacionadministrativa',
            name='tipo_documento',
            field=models.CharField(choices=[('PERSONAL', 'Documentación personal'), ('CBU', 'Comprobante de CBU'), ('PROYECTO', 'Documentación del proyecto')], help_text='Tipo de documentación a subsanar', max_length=20),
        ),
    ]
