# Generated by Django 5.1.7 on 2026-06-14 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0018_doble_ciego_jurado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('puntaje_maximo', models.PositiveIntegerField(default=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios_evaluacion', to='convocatorias.convocatoria')),
            ],
            options={
                'verbose_name': 'Criterio de evaluación',
                'verbose_name_plural': 'Criterios de evaluación',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_puntuar', models.BooleanField(default=False, help_text='Marcar si el comité decide no evaluar este proyecto.')),
                ('fundamentacion', models.TextField(blank=True, help_text='Fundamentación del comité sobre el proyecto.')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('postulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='convocatorias.postulacion')),
                ('ultima_edicion_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_cargadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación de postulación',
                'verbose_name_plural': 'Evaluaciones de postulaciones',
            },
        ),
        migrations.CreateModel(
            name='PuntajeCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveIntegerField(blank=True, null=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='convocatorias.criterioevaluacion')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='convocatorias.evaluacionpostulacion')),
            ],
            options={
                'verbose_name': 'Puntaje por criterio',
                'verbose_name_plural': 'Puntajes por criterio',
                'unique_together': {('evaluacion', 'criterio')},
            },
        ),
    ]
