# Generated by Django 5.1.7 on 2026-06-14 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0019_evaluacion_comite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='cbu',
            field=models.CharField(blank=True, help_text='CBU del productor/presentante (22 dígitos). Solo requerido si la convocatoria lo exige.', max_length=22, validators=[django.core.validators.RegexValidator(message='El CBU debe tener exactamente 22 dígitos numéricos.', regex='^\\d{22}$')], verbose_name='CBU'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='sinopsis_corta',
            field=models.TextField(blank=True, help_text='Máximo 3000 caracteres.', max_length=3000, verbose_name='Logline / Sinopsis corta'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='tipo_proyecto',
            field=models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('', '- Cine -'), ('cine_corto', 'Cortometraje'), ('cine_largo', 'Largometraje'), ('', '- Serie -'), ('serie', 'Serie'), ('serie_web', 'Serie Web'), ('', '- Animacion -'), ('corto_animacion', 'Cortometraje animación'), ('largo_animacion', 'Largometraje animación'), ('serie_animacion', 'Serie animación'), ('serieweb_animacion', 'Serie web animación'), ('videoclip_animacion', 'Videoclip animación'), ('', '- Otros -'), ('tv', 'TV'), ('publicidad', 'Publicidad'), ('videoclip', 'Videoclip'), ('videojuego', 'Videojuego'), ('transmedia', 'Transmedia'), ('otro', 'Otro')], max_length=50),
        ),
    ]
