# Generated by Django 5.1.7 on 2026-06-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0020_cbu_sinopsis_validaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='aporte_propio_pct',
            field=models.DecimalField(decimal_places=4, default='0.10', help_text='Ej: 0.10 para el 10%', max_digits=5, verbose_name='% aporte propio mínimo'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='beneficio_adicional',
            field=models.PositiveIntegerField(default=0, help_text='0 si no aplica', verbose_name='Beneficio adicional (ARS)'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='beneficio_monto',
            field=models.PositiveIntegerField(default=0, help_text='Ej: 15000000', verbose_name='Monto del beneficio IDEA (ARS)'),
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='planilla_template',
            field=models.CharField(blank=True, choices=[('', '— Sin planilla —'), ('01', '01 · Cortometraje ficción'), ('02', '02 · Cortometraje coproducción'), ('03', '03 · Desarrollo'), ('04', '04 · Lab corto'), ('05', '05 · Cine en comunidad'), ('06', '06 · Apoyo rodaje'), ('07', '07 · Apoyo finalización'), ('08', '08 · Cash rebate')], default='', max_length=2, verbose_name='Planilla oficial a usar'),
        ),
    ]
