# Generated by Django 5.1.7 on 2026-06-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0021_config_planilla_financiera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='aporte_propio_pct',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='beneficio_adicional',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='beneficio_monto',
        ),
        migrations.RemoveField(
            model_name='configuracionpostulacion',
            name='planilla_template',
        ),
        migrations.AddField(
            model_name='configuracionpostulacion',
            name='planilla_archivo',
            field=models.FileField(blank=True, help_text='Planilla xlsx que el presentante descarga, completa offline y sube al postularse.', null=True, upload_to='convocatorias/planillas/', verbose_name='Archivo de planilla oficial (.xlsx)'),
        ),
    ]
