# Generated by Django 5.1.7 on 2026-07-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0022_config_planilla_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='honorarios_elenco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Honorarios elenco'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='honorarios_tecnicos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Honorarios técnicos'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='insumos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Insumos'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='otros_honorarios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros honorarios'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='planilla_xlsx',
            field=models.FileField(blank=True, null=True, upload_to='rendiciones/planillas/', verbose_name='Planilla de rendición (.xlsx)'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='servicios_audiovisuales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Servicios audiovisuales'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='servicios_logistica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Servicios / logística'),
        ),
    ]
