# Generated by Django 5.1.7 on 2026-07-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0023_rendicion_impacto_economico'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='honorarios_elenco_cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad — honorarios elenco'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='honorarios_tecnicos_cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad — honorarios técnicos'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='insumos_cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad — insumos'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='otros_honorarios_cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad — otros honorarios'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='servicios_audiovisuales_cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad — servicios audiovisuales'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='servicios_logistica_cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad — servicios / logística'),
        ),
    ]
