# Generated by Django 5.1.7 on 2026-07-12 14:46

from django.db import migrations, models


def backfill_fecha_aprobacion(apps, schema_editor):
    """Para rendiciones ya aprobadas usa la mejor fecha disponible:
    última revisión, o en su defecto la última actualización."""
    Rendicion = apps.get_model("convocatorias", "Rendicion")
    for r in Rendicion.objects.filter(estado="APROBADO", fecha_aprobacion__isnull=True):
        fuente = r.fecha_ultima_revision or r.fecha_actualizacion
        if fuente:
            r.fecha_aprobacion = fuente.date()
            r.save(update_fields=["fecha_aprobacion"])


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0024_rendicion_honorarios_elenco_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_fecha_aprobacion, migrations.RunPython.noop),
    ]
