# Generated by Django 5.1.7 on 2026-07-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0025_rendicion_fecha_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='monto_otorgado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cargar cuando el proyecto resulta seleccionado.', max_digits=12, null=True, verbose_name='Monto otorgado ($)'),
        ),
    ]
