# Generated by Django 5.1.7 on 2026-07-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0026_postulacion_monto_otorgado'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='documentacion_depurada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Documentación depurada el'),
        ),
    ]
