# Generated by Django 5.1.7 on 2026-06-12 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatorias', '0010_drop_inscripcionformacion'),
        ('registro_audiovisual', '0004_juridica_representante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('apellido', models.CharField(blank=True, max_length=120)),
                ('dni', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=60)),
                ('localidad', models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EM', 'El Molinar'), ('ET', 'El Tala'), ('Gi', 'General Güemes'), ('GM', 'General Mosconi'), ('Ga', 'Gaona'), ('Gp', 'Guachipas'), ('Hi', 'Hipólito Yrigoyen'), ('I', 'Iruya'), ('JV', 'Joaquín V. González'), ('LL', 'La Caldera'), ('LC', 'La Candelaria'), ('LV', 'La Viña'), ('LM', 'Las Lajitas'), ('LS', 'Los Toldos'), ('LR', 'Rosario de Lerma'), ('LP', 'La Poma'), ('LQ', 'La Quesera'), ('MA', 'Metán'), ('Mi', 'Molinos'), ('NP', 'Nazareno'), ('OC', 'Orán'), ('Pa', 'Payogasta'), ('Pi', 'Pichanal'), ('Po', 'Posadas'), ('Ri', 'Rivadavia'), ('RN', 'Rosario de la Frontera'), ('RS', 'Rosario de Santa Fe'), ('SA', 'San Antonio de los Cobres'), ('SL', 'San Carlos'), ('SO', 'San Lorenzo'), ('SP', 'San Ramón de la Nueva Orán'), ('ST', 'Santa Victoria Este'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('To', 'Tolombón'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], max_length=20)),
                ('otra_localidad', models.CharField(blank=True, max_length=120)),
                ('vinculo_sector', models.CharField(blank=True, choices=[('sector', 'Trabajo actualmente en el sector audiovisual'), ('empezando', 'Estoy empezando / quiero insertarme'), ('no_sector', 'No, pero quiero capacitarme')], max_length=20)),
                ('declaracion_jurada', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('inscripto', 'Inscripto'), ('admitido', 'Admitido'), ('no_admitido', 'No admitido'), ('lista_espera', 'Lista de espera')], default='inscripto', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria')),
                ('persona_humana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_audiovisual.personahumana')),
                ('persona_juridica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_audiovisual.personajuridica')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción a formación',
                'verbose_name_plural': 'Inscripciones a formación',
                'ordering': ['-fecha'],
                'unique_together': {('user', 'convocatoria')},
            },
        ),
    ]
