# Generated by Django 5.1.7 on 2026-06-14 18:25

import django.db.models.deletion
import formacion.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro_audiovisual', '0006_remove_personajuridica_productor_apellido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvocatoriaFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tipo_formacion', models.CharField(choices=[('ASINCRONICA', 'Asincrónica (link público al curso)'), ('INSCRIPCION_LIBRE', 'Inscripción sin registro audiovisual'), ('INSCRIPCION_REGISTRO', 'Inscripción con registro audiovisual')], default='INSCRIPCION_LIBRE', max_length=25)),
                ('descripcion_corta', models.TextField(blank=True)),
                ('descripcion_larga', models.TextField(blank=True)),
                ('tematica_genero', models.CharField(blank=True, max_length=200)),
                ('requisitos', models.TextField(blank=True)),
                ('beneficios', models.TextField(blank=True)),
                ('bases_pdf', models.FileField(blank=True, null=True, upload_to='formacion/bases/', validators=[formacion.validators.validar_documento_admitido, formacion.validators.validar_tamano_archivo], verbose_name='Bases (PDF / Excel / Planilla)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='formacion/img/')),
                ('url_curso', models.URLField(blank=True, null=True, verbose_name='URL del curso asincrónico')),
                ('url_destino', models.CharField(blank=True, max_length=300)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('bloque_personas', models.CharField(choices=[('FORMADORES', 'Formadores/as'), ('TUTORES', 'Tutores/as'), ('NINGUNO', 'Sin título')], default='FORMADORES', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Convocatoria de formación',
                'verbose_name_plural': 'Convocatorias de formación',
                'ordering': ['orden', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionInscripcionFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_nombre_apellido', models.BooleanField(default=True, verbose_name='Nombre y apellido')),
                ('mostrar_dni', models.BooleanField(default=True, verbose_name='DNI')),
                ('mostrar_genero', models.BooleanField(default=False, verbose_name='Género')),
                ('mostrar_edad', models.BooleanField(default=False, verbose_name='Edad')),
                ('mostrar_telefono', models.BooleanField(default=True, verbose_name='Teléfono')),
                ('mostrar_email', models.BooleanField(default=True, verbose_name='Correo electrónico')),
                ('mostrar_documentacion', models.BooleanField(default=False, verbose_name='Subir documentación')),
                ('convocatoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_inscripcion', to='formacion.convocatoriaformacion')),
            ],
            options={
                'verbose_name': 'Configuración de inscripción (formación)',
                'verbose_name_plural': 'Configuraciones de inscripción (formación)',
            },
        ),
        migrations.CreateModel(
            name='MiembroFormador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='formacion/formadores/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='formacion.convocatoriaformacion')),
            ],
            options={
                'verbose_name': 'Formador/a',
                'verbose_name_plural': 'Formadores/as',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('apellido', models.CharField(blank=True, max_length=120)),
                ('dni', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=60)),
                ('localidad', models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('SC', 'Salta Capital'), ('otro', 'Otro'), ('Ag', 'Aguaray'), ('AB', 'Aguas Blancas'), ('An', 'Angastaco'), ('Ai', 'Animaná'), ('AS', 'Apolinario Saravia'), ('Ca', 'Cachi'), ('Cf', 'Cafayate'), ('CQ', 'Campo Quijano'), ('CS', 'Campo Santo'), ('Ce', 'Cerrillos'), ('Ch', 'Chicoana'), ('CSR', 'Colonia Santa Rosa'), ('CM', 'Coronel Moldes'), ('EB', 'El Bordo'), ('EC', 'El Carril'), ('EG', 'El Galpón'), ('EJ', 'El Jardín'), ('EM', 'El Molinar'), ('ET', 'El Tala'), ('Gi', 'General Güemes'), ('GM', 'General Mosconi'), ('Ga', 'Gaona'), ('Gp', 'Guachipas'), ('Hi', 'Hipólito Yrigoyen'), ('I', 'Iruya'), ('JV', 'Joaquín V. González'), ('LL', 'La Caldera'), ('LC', 'La Candelaria'), ('LV', 'La Viña'), ('LM', 'Las Lajitas'), ('LS', 'Los Toldos'), ('LR', 'Rosario de Lerma'), ('LP', 'La Poma'), ('LQ', 'La Quesera'), ('MA', 'Metán'), ('Mi', 'Molinos'), ('NP', 'Nazareno'), ('OC', 'Orán'), ('Pa', 'Payogasta'), ('Pi', 'Pichanal'), ('Po', 'Posadas'), ('Ri', 'Rivadavia'), ('RN', 'Rosario de la Frontera'), ('RS', 'Rosario de Santa Fe'), ('SA', 'San Antonio de los Cobres'), ('SL', 'San Carlos'), ('SO', 'San Lorenzo'), ('SP', 'San Ramón de la Nueva Orán'), ('ST', 'Santa Victoria Este'), ('Se', 'Seclantás'), ('Ta', 'Tartagal'), ('To', 'Tolombón'), ('Ur', 'Urundel'), ('Va', 'Vaqueros')], max_length=20)),
                ('otra_localidad', models.CharField(blank=True, max_length=120)),
                ('vinculo_sector', models.CharField(blank=True, choices=[('sector', 'Trabajo actualmente en el sector audiovisual'), ('empezando', 'Estoy empezando / quiero insertarme'), ('no_sector', 'No, pero quiero capacitarme')], max_length=20)),
                ('genero', models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('masculino', 'Masculino'), ('femenino', 'Femenino'), ('no_binario', 'No binario'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decirlo')], max_length=20)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('documentacion', models.FileField(blank=True, null=True, upload_to='formacion/documentacion/', validators=[formacion.validators.validar_documento_admitido, formacion.validators.validar_tamano_archivo], verbose_name='Documentación')),
                ('declaracion_jurada', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('inscripto', 'Inscripto'), ('admitido', 'Admitido'), ('no_admitido', 'No admitido'), ('lista_espera', 'Lista de espera')], default='inscripto', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion.convocatoriaformacion')),
                ('persona_humana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_audiovisual.personahumana')),
                ('persona_juridica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_audiovisual.personajuridica')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción a formación',
                'verbose_name_plural': 'Inscripciones a formación',
                'ordering': ['-fecha'],
                'unique_together': {('user', 'convocatoria')},
            },
        ),
    ]
