# Generated by Django 5.1.7 on 2026-06-12 22:43

import convocatorias.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0014_config_inscripcion_campos'),
        ('formacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionformacion',
            name='documentacion',
            field=models.FileField(blank=True, null=True, upload_to='formacion/documentacion/', validators=[convocatorias.validators.validar_documento_admitido, convocatorias.validators.validar_tamano_archivo], verbose_name='Documentación'),
        ),
        migrations.AddField(
            model_name='inscripcionformacion',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionformacion',
            name='genero',
            field=models.CharField(blank=True, choices=[('', '- Seleccionar -'), ('masculino', 'Masculino'), ('femenino', 'Femenino'), ('no_binario', 'No binario'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decirlo')], max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracionInscripcionFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_nombre_apellido', models.BooleanField(default=True, verbose_name='Nombre y apellido')),
                ('mostrar_dni', models.BooleanField(default=True, verbose_name='DNI')),
                ('mostrar_genero', models.BooleanField(default=False, verbose_name='Género')),
                ('mostrar_edad', models.BooleanField(default=False, verbose_name='Edad')),
                ('mostrar_telefono', models.BooleanField(default=True, verbose_name='Teléfono')),
                ('mostrar_email', models.BooleanField(default=True, verbose_name='Correo electrónico')),
                ('mostrar_documentacion', models.BooleanField(default=False, verbose_name='Subir documentación')),
                ('convocatoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_inscripcion_formacion', to='convocatorias.convocatoria')),
            ],
            options={
                'verbose_name': 'Configuración de inscripción (formación)',
                'verbose_name_plural': 'Configuraciones de inscripción (formación)',
            },
        ),
    ]
