# Generated by Django 5.1.7 on 2026-06-14 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionformacion',
            name='estado',
            field=models.CharField(choices=[('inscripto', 'Inscripto'), ('observado', 'Observado'), ('admitido', 'Admitido'), ('no_admitido', 'No admitido'), ('lista_espera', 'Lista de espera')], default='inscripto', max_length=20),
        ),
        migrations.CreateModel(
            name='ObservacionFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Falta DNI, Falta comprobante de pago', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('subsanada', models.BooleanField(default=False)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='formacion.inscripcionformacion')),
            ],
            options={
                'verbose_name': 'Observación administrativa (formación)',
                'verbose_name_plural': 'Observaciones administrativas (formación)',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
