# Generated by Django 5.1.7 on 2026-06-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0002_observacion_formacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoriaformacion',
            name='cupo_maximo',
            field=models.PositiveIntegerField(blank=True, help_text='Dejá en blanco para inscripciones ilimitadas.', null=True, verbose_name='Cupo máximo'),
        ),
    ]
