# Generated by Django 5.1.7 on 2026-07-18 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatorias', '0027_postulacion_documentacion_depurada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('formato', models.CharField(blank=True, choices=[('cortometraje', 'Cortometraje'), ('mediometraje', 'Mediometraje'), ('largometraje', 'Largometraje'), ('unitario', 'Unitario'), ('serie', 'Serie'), ('videoclip', 'Videoclip'), ('experimental', 'Experimental'), ('videojuego', 'Videojuego'), ('otro', 'Otro')], max_length=20)),
                ('genero', models.CharField(blank=True, max_length=100)),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de producción')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('productora', models.CharField(blank=True, max_length=255)),
                ('sinopsis', models.TextField(blank=True)),
                ('estado_produccion', models.CharField(choices=[('desarrollo', 'En desarrollo'), ('produccion', 'En producción'), ('postproduccion', 'En postproducción'), ('finalizada', 'Finalizada')], default='desarrollo', max_length=20)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to=settings.AUTH_USER_MODEL, verbose_name='Titular de la obra')),
                ('postulaciones', models.ManyToManyField(blank=True, related_name='obras', to='convocatorias.postulacion', verbose_name='Postulaciones vinculadas')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('apoyo', 'Otro apoyo'), ('premio', 'Premio / reconocimiento'), ('festival', 'Festival'), ('mercado', 'Mercado'), ('laboratorio', 'Laboratorio')], max_length=20)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del evento / apoyo')),
                ('anio', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('lugar', models.CharField(blank=True, max_length=150, verbose_name='Ciudad / lugar')),
                ('entidad', models.CharField(blank=True, max_length=255)),
                ('edicion', models.CharField(blank=True, max_length=100)),
                ('resultado', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('adjunto', models.FileField(blank=True, help_text='Comprobante / constancia (opcional).', upload_to='gps/hitos/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('hito_origen', models.ForeignKey(blank=True, help_text='P. ej. el festival del que proviene este premio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios', to='gps.hito', verbose_name='Surge del hito')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='gps.obra')),
            ],
            options={
                'verbose_name': 'Hito de trayectoria',
                'verbose_name_plural': 'Hitos de trayectoria',
                'ordering': ['-anio', '-fecha'],
            },
        ),
    ]
