# Generated by Django 5.1.7 on 2026-07-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hito',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hitos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hito',
            name='estado',
            field=models.CharField(blank=True, choices=[('postulado', 'Postulado'), ('preseleccionado', 'Preseleccionado'), ('seleccionado', 'Seleccionado'), ('participante', 'Participante'), ('nominado', 'Nominado'), ('ganador', 'Ganador'), ('no_seleccionado', 'No seleccionado'), ('finalizado', 'Finalizado')], max_length=20),
        ),
        migrations.AddField(
            model_name='obra',
            name='anio_finalizacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de finalización'),
        ),
        migrations.AddField(
            model_name='obra',
            name='anio_inicio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de inicio'),
        ),
        migrations.AddField(
            model_name='obra',
            name='duracion',
            field=models.CharField(blank=True, help_text="Duración estimada o definitiva (p. ej. '12 min').", max_length=50, verbose_name='Duración'),
        ),
        migrations.AddField(
            model_name='obra',
            name='enlace',
            field=models.URLField(blank=True, help_text='Tráiler, teaser o sitio del proyecto.', verbose_name='Enlace del proyecto'),
        ),
        migrations.AddField(
            model_name='obra',
            name='localidad',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='obra',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='gps/portadas/', verbose_name='Imagen / afiche / portada'),
        ),
        migrations.AddField(
            model_name='obra',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='obra',
            name='seguimiento',
            field=models.CharField(choices=[('activa', 'Activa'), ('sin_novedades', 'Sin novedades'), ('cerrado', 'Seguimiento cerrado')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='hito',
            name='tipo',
            field=models.CharField(choices=[('apoyo', 'Otro apoyo'), ('premio', 'Premio / reconocimiento'), ('festival', 'Festival'), ('mercado', 'Mercado'), ('laboratorio', 'Laboratorio'), ('estreno', 'Estreno o exhibición'), ('distribucion', 'Distribución o lanzamiento')], max_length=20),
        ),
    ]
