# Generated by Django 5.1.7 on 2026-07-19 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0002_hito_creado_por_hito_estado_obra_anio_finalizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guion', models.TextField(blank=True, verbose_name='Guion')),
                ('produccion', models.TextField(blank=True, verbose_name='Producción')),
                ('otros_creditos', models.TextField(blank=True, help_text='Edición, sonido, montaje, música, animación, etc.', verbose_name='Otros créditos')),
                ('elenco', models.TextField(blank=True, verbose_name='Elenco principal')),
                ('pais', models.CharField(blank=True, max_length=120, verbose_name='País de producción')),
                ('locaciones_rodaje', models.TextField(blank=True, verbose_name='Locaciones de rodaje')),
                ('idioma', models.CharField(blank=True, max_length=120)),
                ('detalle_financiamiento', models.TextField(blank=True, help_text='Instituciones, tipo de apoyo, año.', verbose_name='Detalle de financiamiento')),
                ('resolucion', models.CharField(blank=True, choices=[('SD', 'SD'), ('HD', 'HD'), ('FULLHD', 'Full HD'), ('2K', '2K'), ('4K', '4K'), ('5K', '5K'), ('otros', 'Otros')], max_length=10)),
                ('relacion_aspecto', models.CharField(blank=True, choices=[('4:3', '4:3'), ('16:9', '16:9'), ('17:9', '17:9'), ('1.85:1', '1.85:1'), ('2.40:1', '2.40:1')], max_length=10)),
                ('codec_especificaciones', models.TextField(blank=True, verbose_name='Codec / formato / especificaciones técnicas')),
                ('caracteristicas_color', models.CharField(blank=True, max_length=255)),
                ('caracteristicas_sonido', models.CharField(blank=True, help_text='Canales, sistema, etc.', max_length=255, verbose_name='Características de sonido')),
                ('medio_entrega', models.CharField(blank=True, choices=[('pen_drive', 'Pen drive'), ('memoria', 'Memoria externa'), ('transferencia', 'Transferencia virtual')], max_length=20)),
                ('copyright', models.TextField(blank=True, verbose_name='Copyright / propiedad intelectual')),
                ('notas', models.TextField(blank=True, help_text='Agradecimientos, auspicios, disponibilidad web, etc.', verbose_name='Notas')),
                ('usa_material_archivo', models.BooleanField(blank=True, null=True, verbose_name='¿Incluye imágenes de archivo?')),
                ('origen_archivo', models.TextField(blank=True, help_text='Estatal, privado, personal, televisión, prensa, etc.', verbose_name='Origen del material de archivo')),
                ('gestion_archivo', models.TextField(blank=True, help_text='Cómo se obtuvieron las copias y dónde se localizan.', verbose_name='Gestión del material de archivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('obra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='gps.obra')),
            ],
            options={
                'verbose_name': 'Ficha técnica',
                'verbose_name_plural': 'Fichas técnicas',
            },
        ),
    ]
