# Generated by Django 5.1.7 on 2026-07-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0003_fichatecnica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='productora',
            new_name='produccion',
        ),
        migrations.AlterField(
            model_name='obra',
            name='produccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Producción'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='duracion',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Duración estimada o definitiva, en minutos.', null=True, verbose_name='Duración (minutos)'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='genero',
            field=models.CharField(blank=True, choices=[('ficcion', 'Ficción'), ('documental', 'Documental'), ('noficcion', 'No ficción'), ('educativo', 'Educativo'), ('deportivo', 'Deportivo'), ('simulacion', 'Simulación'), ('ludico', 'Lúdico'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de obra'),
        ),
    ]
