# Generated by Django 5.1.7 on 2026-07-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gps', '0004_remove_obra_productora_obra_produccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='direccion_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label': 'registro_audiovisual', 'model__in': ('personahumana', 'personajuridica')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='obra',
            name='direccion_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='produccion_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label': 'registro_audiovisual', 'model__in': ('personahumana', 'personajuridica')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='obra',
            name='produccion_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
