# Generated by Django 5.1.7 on 2026-07-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0005_obra_direccion_content_type_obra_direccion_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='provincia',
        ),
    ]
