# Generated by Django 5.1.7 on 2026-07-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0006_remove_obra_localidad_remove_obra_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='anio',
        ),
    ]
