# Generated by Django 5.1.7 on 2026-07-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0007_remove_obra_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hito',
            name='anio',
            field=models.PositiveSmallIntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='hito',
            name='moneda',
            field=models.CharField(blank=True, choices=[('ARS', 'Peso argentino (ARS)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)'), ('BRL', 'Real (BRL)'), ('otra', 'Otra')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hito',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo si el hito implicó un monto (premio, apoyo, etc.).', max_digits=14, null=True, verbose_name='Monto'),
        ),
    ]
