# Generated by Django 5.1.7 on 2026-07-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0008_alter_hito_anio_alter_hito_moneda_alter_hito_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hito',
            name='moneda',
            field=models.CharField(blank=True, choices=[('ARS', 'Peso argentino (ARS)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)'), ('BRL', 'Real (BRL)')], max_length=10),
        ),
    ]
