# Generated by Django 5.1.7 on 2026-07-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gps', '0009_alter_hito_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnica',
            name='guion',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='otros_creditos',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='produccion',
        ),
        migrations.CreateModel(
            name='CreditoFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('guionista', 'Guionista/s'), ('productor', 'Productor/a'), ('fotografia', 'Director/a de fotografía'), ('arte', 'Director/a de arte'), ('montaje', 'Montajista'), ('sonido', 'Director/a de sonido'), ('otro', 'Otro crédito')], max_length=20)),
                ('detalle', models.CharField(blank=True, help_text="Solo para 'Otro crédito': especificá el rol.", max_length=150, verbose_name='Rol')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('nombre_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='gps.fichatecnica')),
                ('nombre_content_type', models.ForeignKey(blank=True, limit_choices_to={'app_label': 'registro_audiovisual', 'model__in': ('personahumana', 'personajuridica')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Crédito de ficha técnica',
                'verbose_name_plural': 'Créditos de ficha técnica',
                'ordering': ['cargo', 'id'],
            },
        ),
    ]
