# Generated by Django 5.1.7 on 2026-07-26 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0010_remove_fichatecnica_guion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título anterior')),
                ('anio_hasta', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Se llamó así hasta')),
                ('nota', models.CharField(blank=True, help_text='P. ej. "título de desarrollo" o "título de festival".', max_length=255)),
                ('automatico', models.BooleanField(default=False, verbose_name='Registrado automáticamente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos_anteriores', to='gps.obra')),
            ],
            options={
                'verbose_name': 'Título anterior',
                'verbose_name_plural': 'Títulos anteriores',
                'ordering': ['-anio_hasta', '-id'],
                'constraints': [models.UniqueConstraint(fields=('obra', 'titulo'), name='gps_titulo_anterior_unico')],
            },
        ),
    ]
