# Generated by Django 5.1.7 on 2026-07-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0011_tituloanterior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='subtitulo',
        ),
    ]
