# Generated by Django 5.1.7 on 2026-07-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0012_remove_obra_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre/s y Apellido/s del Director/a'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='produccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre/s y Apellido/s del Productor/a'),
        ),
    ]
