# Generated by Django 5.1.7 on 2026-01-18 18:36

import django.db.models.deletion
import exencion.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatorias', '0001_initial'),
        ('registro_audiovisual', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PadronPublicoExencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Padrón público de exención',
                'verbose_name_plural': 'Padrón público de exención',
            },
        ),
        migrations.CreateModel(
            name='Exencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_razon_social', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cuit', models.CharField(max_length=20)),
                ('domicilio_fiscal', models.CharField(max_length=255)),
                ('localidad_fiscal', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal_fiscal', models.CharField(blank=True, max_length=10, null=True)),
                ('actividad_dgr', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='ENVIADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='exencion/certificados/')),
                ('convocatoria', models.ForeignKey(blank=True, help_text='Puede venir de una convocatoria o ser independiente', null=True, on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria')),
                ('persona_humana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_audiovisual.personahumana')),
                ('persona_juridica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_audiovisual.personajuridica')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exención impositiva',
                'verbose_name_plural': 'Exenciones impositivas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ExencionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='exencion/documentos/', validators=[exencion.models.validar_pdf, exencion.models.validar_tamano_5mb])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('es_subsanacion', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADO', 'Enviado')], db_index=True, default='PENDIENTE', max_length=10)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('exencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='exencion.exencion')),
            ],
            options={
                'verbose_name': 'Documento de exención',
                'verbose_name_plural': 'Documentos de exención',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ObservacionAdministrativaExencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('GENERAL', 'Documentación general'), ('FISCAL', 'Documentación fiscal'), ('IDENTIDAD', 'Identidad / Personería'), ('OTRO', 'Otro')], default='GENERAL', help_text='Tipo de documentación a subsanar', max_length=20)),
                ('descripcion', models.CharField(help_text='Ej: Falta constancia DGR, CUIT ilegible, Acta sin firma, etc.', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('subsanada', models.BooleanField(default=False)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='exencion.exencion')),
            ],
            options={
                'verbose_name': 'Observación administrativa (Exención)',
                'verbose_name_plural': 'Observaciones administrativas (Exención)',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
