# Generated by Django 5.1.7 on 2025-12-14 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatorias', '0001_initial'),
        ('registro_audiovisual', '0007_alter_personahumana_actividad_dgr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_razon_social', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cuit', models.CharField(max_length=20)),
                ('domicilio_fiscal', models.CharField(max_length=255)),
                ('actividad_dgr', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='ENVIADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='exencion/certificados/')),
                ('convocatoria', models.ForeignKey(blank=True, help_text='Puede venir de una convocatoria o ser independiente', null=True, on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria')),
                ('persona_humana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_audiovisual.personahumana')),
                ('persona_juridica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_audiovisual.personajuridica')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exención impositiva',
                'verbose_name_plural': 'Exenciones impositivas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ExencionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='exencion/documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('exencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='exencion.exencion')),
            ],
            options={
                'verbose_name': 'Documento de exención',
                'verbose_name_plural': 'Documentos de exención',
            },
        ),
    ]
