# Generated by Django 5.1.7 on 2025-12-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exencion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exencion',
            name='codigo_postal_fiscal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='exencion',
            name='localidad_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
