# Generated by Django 5.1.7 on 2025-12-12 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0011_convocatoria_url_curso_inscripcioncurso'),
        ('exencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exencion',
            name='actividad_dgr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exencion',
            name='convocatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria'),
        ),
        migrations.AlterField(
            model_name='exencion',
            name='cuit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='exencion',
            name='domicilio_fiscal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exencion',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='exencion',
            name='nombre_razon_social',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
