# Generated by Django 5.1.7 on 2026-03-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exencion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20),
        ),
    ]
