# Generated by Django 5.1.7 on 2026-01-16 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exencion', '0002_exencion_codigo_postal_fiscal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionAdministrativaExencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('GENERAL', 'Documentación general'), ('FISCAL', 'Documentación fiscal'), ('IDENTIDAD', 'Identidad / Personería'), ('OTRO', 'Otro')], default='GENERAL', help_text='Tipo de documentación a subsanar', max_length=20)),
                ('descripcion', models.CharField(help_text='Ej: Falta constancia DGR, CUIT ilegible, Acta sin firma, etc.', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('subsanada', models.BooleanField(default=False)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='exencion.exencion')),
            ],
            options={
                'verbose_name': 'Observación administrativa (Exención)',
                'verbose_name_plural': 'Observaciones administrativas (Exención)',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
