# Generated by Django 5.1.7 on 2025-12-13 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0013_alter_postulacionidea_tipo_proyecto'),
        ('exencion', '0002_alter_exencion_actividad_dgr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exencion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Exención impositiva', 'verbose_name_plural': 'Exenciones impositivas'},
        ),
        migrations.AlterModelOptions(
            name='exenciondocumento',
            options={'verbose_name': 'Documento de exención', 'verbose_name_plural': 'Documentos de exención'},
        ),
        migrations.AlterField(
            model_name='exencion',
            name='actividad_dgr',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exencion',
            name='convocatoria',
            field=models.ForeignKey(blank=True, help_text='Puede venir de una convocatoria o ser independiente', null=True, on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria'),
        ),
        migrations.AlterField(
            model_name='exencion',
            name='cuit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='exencion',
            name='domicilio_fiscal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exencion',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='exencion',
            name='nombre_razon_social',
            field=models.CharField(max_length=255),
        ),
    ]
