# Generated by Django 5.1.7 on 2026-06-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exencion', '0002_alter_exencion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='exenciondocumento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CV', 'Curriculum Vitae'), ('DNI', 'DNI (frente y dorso)'), ('CONSTANCIA_ARCA', 'Constancia de inscripción en ARCA')], max_length=20, null=True),
        ),
    ]
