# Generated by Django 5.1.7 on 2026-01-16 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exencion', '0003_observacionadministrativaexencion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exenciondocumento',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento de exención', 'verbose_name_plural': 'Documentos de exención'},
        ),
        migrations.AddField(
            model_name='exenciondocumento',
            name='observacion',
            field=models.ForeignKey(blank=True, help_text='Observación administrativa que motivó la carga (si corresponde).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subsanados', to='exencion.observacionadministrativaexencion'),
        ),
        migrations.AddField(
            model_name='exenciondocumento',
            name='origen',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('SUBSANACION', 'Subsanación')], db_index=True, default='NORMAL', help_text='Normal = documentación inicial. Subsanación = documentación enviada por observación.', max_length=20),
        ),
    ]
