# Generated by Django 5.1.7 on 2026-07-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exencion', '0004_exencion_estado_observada'),
    ]

    operations = [
        migrations.AddField(
            model_name='exencion',
            name='documentacion_depurada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Documentación depurada el'),
        ),
    ]
