# Generated by Django 5.1.7 on 2026-01-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exencion', '0004_alter_exenciondocumento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exenciondocumento',
            options={'verbose_name': 'Documento de exención', 'verbose_name_plural': 'Documentos de exención'},
        ),
        migrations.RemoveField(
            model_name='exenciondocumento',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='exenciondocumento',
            name='origen',
        ),
        migrations.AddField(
            model_name='exenciondocumento',
            name='es_subsanacion',
            field=models.BooleanField(default=False),
        ),
    ]
