# Generated by Django 5.1.7 on 2026-01-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exencion', '0005_alter_exenciondocumento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exenciondocumento',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento de exención', 'verbose_name_plural': 'Documentos de exención'},
        ),
        migrations.AddField(
            model_name='exenciondocumento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADO', 'Enviado')], db_index=True, default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='exenciondocumento',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
