# Generated by Django 5.1.7 on 2026-01-17 19:29

import exencion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exencion', '0006_alter_exenciondocumento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exenciondocumento',
            name='archivo',
            field=models.FileField(upload_to='exencion/documentos/', validators=[exencion.models.validar_pdf, exencion.models.validar_tamano_5mb]),
        ),
    ]
