# Generated by Django 5.1.7 on 2026-01-18 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exencion', '0007_alter_exenciondocumento_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadronPublicoExencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Padrón público de exención',
                'verbose_name_plural': 'Padrón público de exención',
            },
        ),
    ]
